<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Portugal',
                'iso_code' => 'PT',
                'iso_code_3' => 'PRT',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => false,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'D7 Visa',
                'min_income_for_visa' => 1062.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'Portugal offers NHR (Non-Habitual Resident) status for 10 years with significant tax benefits. Income tax rates range from 14.5% to 48%.',
                'visa_requirements' => 'Passive income from external sources, €1,062 monthly minimum.',
                'avg_monthly_cost_of_living' => 1200.00,
                'official_tax_authority_url' => 'https://www.portaldasfinancas.gov.pt',
                'slug' => 'portugal',
                'meta_description' => 'Complete tax guide for Portugal - rates, visa requirements, and tax residency rules.',
                'is_featured' => true,
                'popularity_rank' => 1,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'Spain',
                'iso_code' => 'ES',
                'iso_code_3' => 'ESP',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => false,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Digital Nomad Visa',
                'min_income_for_visa' => 2300.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'Spain taxes worldwide income for residents. Progressive rates from 19% to 45%. Special regimes available for certain workers.',
                'visa_requirements' => 'Remote income, €2,300 monthly minimum, health insurance.',
                'avg_monthly_cost_of_living' => 1500.00,
                'official_tax_authority_url' => 'https://www.agenciatributaria.es',
                'slug' => 'spain',
                'meta_description' => 'Spanish tax system guide - progressive rates, digital nomad visa, and tax residency requirements.',
                'is_featured' => true,
                'popularity_rank' => 2,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'United States',
                'iso_code' => 'US',
                'iso_code_3' => 'USA',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => true,
                'has_digital_nomad_visa' => false,
                'digital_nomad_visa_name' => null,
                'min_income_for_visa' => null,
                'visa_income_period' => null,
                'tax_residency_days' => 0,
                'counts_arrival_day' => true,
                'counts_departure_day' => true,
                'considers_center_of_vital_interests' => false,
                'tax_system_notes' => 'US citizens are taxed on worldwide income regardless of residence. Federal rates 10% to 37%. Also state taxes vary.',
                'visa_requirements' => 'Visa requirements vary by country of origin.',
                'avg_monthly_cost_of_living' => 3000.00,
                'official_tax_authority_url' => 'https://www.irs.gov',
                'slug' => 'united-states',
                'meta_description' => 'US federal and state tax information - worldwide income taxation, rates, and filing requirements.',
                'is_featured' => true,
                'popularity_rank' => 3,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'United Kingdom',
                'iso_code' => 'GB',
                'iso_code_3' => 'GBR',
                'currency_code' => 'GBP',
                'currency_symbol' => '£',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => true,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Visa for Tech Workers',
                'min_income_for_visa' => 5000.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'UK taxes residents on UK and overseas income. Personal allowance £12,570. Rates: 20%, 40%, 45%.',
                'visa_requirements' => 'Skilled worker visa available for tech roles.',
                'avg_monthly_cost_of_living' => 2500.00,
                'official_tax_authority_url' => 'https://www.gov.uk/government/organisations/hm-revenue-customs',
                'slug' => 'united-kingdom',
                'meta_description' => 'UK tax guide - income tax rates, personal allowance, and non-resident taxation.',
                'is_featured' => true,
                'popularity_rank' => 4,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'Germany',
                'iso_code' => 'DE',
                'iso_code_3' => 'DEU',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => true,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Freelance Visa',
                'min_income_for_visa' => 1800.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'Germany has progressive income tax from 0% to 45%. Solidarity surcharge of 5.5% applies. Corporate tax 30%.',
                'visa_requirements' => 'Freelance professionals can apply for residence permits. Self-employment expected.',
                'avg_monthly_cost_of_living' => 1800.00,
                'official_tax_authority_url' => 'https://www.bzst.bund.de',
                'slug' => 'germany',
                'meta_description' => 'German tax system - income tax rates, freelance visa options, and residence requirements.',
                'is_featured' => true,
                'popularity_rank' => 5,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'France',
                'iso_code' => 'FR',
                'iso_code_3' => 'FRA',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => true,
                'has_digital_nomad_visa' => false,
                'digital_nomad_visa_name' => null,
                'min_income_for_visa' => null,
                'visa_income_period' => null,
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'France taxes residents on worldwide income. Progressive rates from 0% to 45%. Generous deductions available.',
                'visa_requirements' => 'Standard EU/non-EU visa requirements apply.',
                'avg_monthly_cost_of_living' => 2000.00,
                'official_tax_authority_url' => 'https://www.impots.gouv.fr',
                'slug' => 'france',
                'meta_description' => 'French income tax guide - rates, deductions, and tax residency rules for 2026.',
                'is_featured' => true,
                'popularity_rank' => 6,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'Thailand',
                'iso_code' => 'TH',
                'iso_code_3' => 'THA',
                'currency_code' => 'THB',
                'currency_symbol' => '฿',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => false,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Elite Visa / LTR Visa',
                'min_income_for_visa' => 2000.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 180,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'Thailand taxes residents (180+ days) on Thailand-sourced income only. Foreign income is not taxed. Rates 5% to 37%.',
                'visa_requirements' => 'Elite Visa (costly but includes benefits). Long Term Resident (LTR) visa from Thailand Board of Investment.',
                'avg_monthly_cost_of_living' => 1000.00,
                'official_tax_authority_url' => 'https://www.rd.go.th',
                'slug' => 'thailand',
                'meta_description' => 'Thailand tax guide - tax residency, Elite visa, and digital nomad visa options.',
                'is_featured' => true,
                'popularity_rank' => 7,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'Mexico',
                'iso_code' => 'MX',
                'iso_code_3' => 'MEX',
                'currency_code' => 'MXN',
                'currency_symbol' => '$',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => true,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Temporal Visa',
                'min_income_for_visa' => 2700.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => true,
                'tax_system_notes' => 'Mexico taxes residents on worldwide income. Progressive rates 1.92% to 35%. Foreign-earned income may have exemptions.',
                'visa_requirements' => 'Temporal visa for 4 years with sufficient income. Pensioners qualify with $2,700 monthly.',
                'avg_monthly_cost_of_living' => 1200.00,
                'official_tax_authority_url' => 'https://www.sat.gob.mx',
                'slug' => 'mexico',
                'meta_description' => 'Mexico tax residency and visa guide - income requirements, tax rates, and filing for 2026.',
                'is_featured' => true,
                'popularity_rank' => 8,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'Dubai / UAE',
                'iso_code' => 'AE',
                'iso_code_3' => 'ARE',
                'currency_code' => 'AED',
                'currency_symbol' => 'د.إ',
                'has_progressive_tax' => false,
                'flat_tax_rate' => 0.00,
                'taxes_worldwide_income' => false,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Virtual Working Program',
                'min_income_for_visa' => 0.00,
                'visa_income_period' => 'annual',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => false,
                'tax_system_notes' => 'UAE has NO personal income tax. 0% tax on worldwide income. Corporate tax only 9% (with exemptions).',
                'visa_requirements' => 'Virtual Working Program - remote work only. Golden visa available for various categories.',
                'avg_monthly_cost_of_living' => 2500.00,
                'official_tax_authority_url' => 'https://www.fta.gov.ae',
                'slug' => 'dubai-uae',
                'meta_description' => 'UAE zero-income tax guide - visa options, corporate tax, and benefits for digital nomads.',
                'is_featured' => true,
                'popularity_rank' => 9,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
            [
                'name' => 'Singapore',
                'iso_code' => 'SG',
                'iso_code_3' => 'SGP',
                'currency_code' => 'SGD',
                'currency_symbol' => '$',
                'has_progressive_tax' => true,
                'flat_tax_rate' => null,
                'taxes_worldwide_income' => false,
                'has_digital_nomad_visa' => true,
                'digital_nomad_visa_name' => 'Tech Passes',
                'min_income_for_visa' => 12000.00,
                'visa_income_period' => 'monthly',
                'tax_residency_days' => 183,
                'counts_arrival_day' => true,
                'counts_departure_day' => false,
                'considers_center_of_vital_interests' => false,
                'tax_system_notes' => 'Singapore taxes only Singapore-source income. Progressive rates 0% to 22%. Foreign-earned income not taxed.',
                'visa_requirements' => 'Tech passes for startup founders and tech experts. Minimum S$12,000 monthly income.',
                'avg_monthly_cost_of_living' => 3000.00,
                'official_tax_authority_url' => 'https://www.iras.gov.sg',
                'slug' => 'singapore',
                'meta_description' => 'Singapore tax guide for digital nomads - zero tax on foreign income, visa options, and rates.',
                'is_featured' => true,
                'popularity_rank' => 10,
                'is_active' => true,
                'data_last_updated' => 2026,
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
