<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $countries = [
            // 1. Portugal
            ['name'=>'Portugal','iso_code'=>'PT','iso_code_3'=>'PRT','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'D7 Visa','min_income_for_visa'=>1062.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'NHR regime for 10 years. Progressive rates 12.5%-48%. Solidarity surcharge above €80k.','visa_requirements'=>'Passive income, €1,062/month minimum.','avg_monthly_cost_of_living'=>1200.00,'official_tax_authority_url'=>'https://www.portaldasfinancas.gov.pt','slug'=>'portugal','meta_description'=>'Portugal tax guide - rates, NHR regime, D7 visa, and residency rules for 2026.','is_featured'=>true,'popularity_rank'=>1,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 2. Spain
            ['name'=>'Spain','iso_code'=>'ES','iso_code_3'=>'ESP','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>2300.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 19%-47% (state+regional). Beckham Law for new residents.','visa_requirements'=>'Remote income, €2,300/month, health insurance.','avg_monthly_cost_of_living'=>1500.00,'official_tax_authority_url'=>'https://www.agenciatributaria.es','slug'=>'spain','meta_description'=>'Spain tax guide - progressive rates, digital nomad visa, and Beckham Law.','is_featured'=>true,'popularity_rank'=>2,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 3. United States
            ['name'=>'United States','iso_code'=>'US','iso_code_3'=>'USA','currency_code'=>'USD','currency_symbol'=>'$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>0,'counts_arrival_day'=>true,'counts_departure_day'=>true,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Citizens taxed worldwide regardless of residence. Federal 10%-37% + state taxes. FEIE available.','visa_requirements'=>'Varies by nationality.','avg_monthly_cost_of_living'=>3000.00,'official_tax_authority_url'=>'https://www.irs.gov','slug'=>'united-states','meta_description'=>'US federal tax guide - worldwide taxation, FEIE, and state tax overview.','is_featured'=>true,'popularity_rank'=>3,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 4. United Kingdom
            ['name'=>'United Kingdom','iso_code'=>'GB','iso_code_3'=>'GBR','currency_code'=>'GBP','currency_symbol'=>'£','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Personal allowance £12,570. Rates 20%-45%. National Insurance contributions apply.','visa_requirements'=>'Skilled worker visa for employment.','avg_monthly_cost_of_living'=>2500.00,'official_tax_authority_url'=>'https://www.gov.uk/government/organisations/hm-revenue-customs','slug'=>'united-kingdom','meta_description'=>'UK tax guide - income rates, personal allowance, and NI contributions.','is_featured'=>true,'popularity_rank'=>4,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 5. Germany
            ['name'=>'Germany','iso_code'=>'DE','iso_code_3'=>'DEU','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Freelance Visa','min_income_for_visa'=>1800.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 14%-45%. Basic allowance €12,348. Solidarity surcharge 5.5% for high earners.','visa_requirements'=>'Freelance visa for self-employed professionals.','avg_monthly_cost_of_living'=>1800.00,'official_tax_authority_url'=>'https://www.bzst.bund.de','slug'=>'germany','meta_description'=>'Germany tax guide - progressive rates, freelance visa, and solidarity surcharge.','is_featured'=>true,'popularity_rank'=>5,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 6. France
            ['name'=>'France','iso_code'=>'FR','iso_code_3'=>'FRA','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-45%. Family quotient system. Surtax for high incomes.','visa_requirements'=>'Standard EU/non-EU visa requirements.','avg_monthly_cost_of_living'=>2000.00,'official_tax_authority_url'=>'https://www.impots.gouv.fr','slug'=>'france','meta_description'=>'France tax guide - progressive rates, family quotient, and residency rules.','is_featured'=>true,'popularity_rank'=>6,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 7. Thailand
            ['name'=>'Thailand','iso_code'=>'TH','iso_code_3'=>'THA','currency_code'=>'THB','currency_symbol'=>'฿','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'LTR Visa','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>180,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Residents (180+ days) taxed on Thai-source income. Rates 0%-35%.','visa_requirements'=>'LTR visa or Elite visa. Proof of income required.','avg_monthly_cost_of_living'=>1000.00,'official_tax_authority_url'=>'https://www.rd.go.th','slug'=>'thailand','meta_description'=>'Thailand tax guide - LTR visa, Elite visa, and territorial taxation.','is_featured'=>true,'popularity_rank'=>7,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 8. Mexico
            ['name'=>'Mexico','iso_code'=>'MX','iso_code_3'=>'MEX','currency_code'=>'MXN','currency_symbol'=>'$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Temporal Visa','min_income_for_visa'=>2700.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 1.92%-35%. Residents taxed on worldwide income.','visa_requirements'=>'Temporal visa, $2,700/month minimum income.','avg_monthly_cost_of_living'=>1200.00,'official_tax_authority_url'=>'https://www.sat.gob.mx','slug'=>'mexico','meta_description'=>'Mexico tax guide - ISR rates, temporal visa, and residency rules.','is_featured'=>true,'popularity_rank'=>8,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 9. UAE
            ['name'=>'United Arab Emirates','iso_code'=>'AE','iso_code_3'=>'ARE','currency_code'=>'AED','currency_symbol'=>'د.إ','has_progressive_tax'=>false,'flat_tax_rate'=>0.00,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Virtual Working Program','min_income_for_visa'=>3500.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Zero personal income tax. Corporate tax 9% with exemptions.','visa_requirements'=>'Virtual Working Program or Golden Visa.','avg_monthly_cost_of_living'=>2500.00,'official_tax_authority_url'=>'https://www.tax.gov.ae','slug'=>'uae','meta_description'=>'UAE zero income tax guide - visa options and benefits for digital nomads.','is_featured'=>true,'popularity_rank'=>9,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 10. Singapore
            ['name'=>'Singapore','iso_code'=>'SG','iso_code_3'=>'SGP','currency_code'=>'SGD','currency_symbol'=>'S$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Tech.Pass','min_income_for_visa'=>12000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Only Singapore-source income taxed. Progressive 0%-24%.','visa_requirements'=>'Tech.Pass for founders/experts. S$12,000/month minimum.','avg_monthly_cost_of_living'=>3000.00,'official_tax_authority_url'=>'https://www.iras.gov.sg','slug'=>'singapore','meta_description'=>'Singapore tax guide - territorial taxation, Tech.Pass, and low rates.','is_featured'=>true,'popularity_rank'=>10,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 11. Estonia
            ['name'=>'Estonia','iso_code'=>'EE','iso_code_3'=>'EST','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>false,'flat_tax_rate'=>24.00,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>4500.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Flat 24% (2026). Non-taxable income up to €7,849. E-Residency program.','visa_requirements'=>'€4,500/month gross income minimum.','avg_monthly_cost_of_living'=>1200.00,'official_tax_authority_url'=>'https://www.emta.ee','slug'=>'estonia','meta_description'=>'Estonia tax guide - flat rate, e-Residency, and digital nomad visa.','is_featured'=>true,'popularity_rank'=>11,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 12. Croatia
            ['name'=>'Croatia','iso_code'=>'HR','iso_code_3'=>'HRV','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>2540.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 20%-30% (default). DN visa holders exempt from Croatian income tax on foreign income.','visa_requirements'=>'Foreign employer/clients only. Valid up to 18 months.','avg_monthly_cost_of_living'=>1100.00,'official_tax_authority_url'=>'https://www.porezna-uprava.hr','slug'=>'croatia','meta_description'=>'Croatia tax guide - digital nomad visa with tax exemption, progressive rates.','is_featured'=>true,'popularity_rank'=>12,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 13. Greece
            ['name'=>'Greece','iso_code'=>'GR','iso_code_3'=>'GRC','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>3500.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 9%-44% (2026). 50% tax reduction for new residents (Article 5C) for 7 years.','visa_requirements'=>'€3,500/month, health insurance.','avg_monthly_cost_of_living'=>1100.00,'official_tax_authority_url'=>'https://www.aade.gr','slug'=>'greece','meta_description'=>'Greece tax guide - 50% tax reduction for new residents, progressive rates.','is_featured'=>true,'popularity_rank'=>13,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 14. Italy
            ['name'=>'Italy','iso_code'=>'IT','iso_code_3'=>'ITA','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>2333.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'IRPEF 23%-43% (2026: 33% middle rate). Regime Forfettario 5% flat for 5 years. Impatriates 50% exemption.','visa_requirements'=>'€28,000/year minimum income.','avg_monthly_cost_of_living'=>1400.00,'official_tax_authority_url'=>'https://www.agenziaentrate.gov.it','slug'=>'italy','meta_description'=>'Italy tax guide - IRPEF rates, Regime Forfettario, and impatriate benefits.','is_featured'=>true,'popularity_rank'=>14,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 15. Netherlands
            ['name'=>'Netherlands','iso_code'=>'NL','iso_code_3'=>'NLD','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 37.1%-49.5%. 30% ruling for skilled migrants (30% salary tax-free).','visa_requirements'=>'Self-employed residence permit available.','avg_monthly_cost_of_living'=>2000.00,'official_tax_authority_url'=>'https://www.belastingdienst.nl','slug'=>'netherlands','meta_description'=>'Netherlands tax guide - progressive rates, 30% ruling for expats.','is_featured'=>true,'popularity_rank'=>15,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 16. Japan
            ['name'=>'Japan','iso_code'=>'JP','iso_code_3'=>'JPN','currency_code'=>'JPY','currency_symbol'=>'¥','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>8333.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'National 5%-45% + local 10%. Surtax 2.1% on national tax.','visa_requirements'=>'Annual income ¥10M+ ($100K), max 6 months.','avg_monthly_cost_of_living'=>2200.00,'official_tax_authority_url'=>'https://www.nta.go.jp','slug'=>'japan','meta_description'=>'Japan tax guide - national and local rates, digital nomad visa.','is_featured'=>false,'popularity_rank'=>16,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 17. Canada
            ['name'=>'Canada','iso_code'=>'CA','iso_code_3'=>'CAN','currency_code'=>'CAD','currency_symbol'=>'C$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Federal 14%-33% + provincial. 2026 lowest bracket drops to 14%.','visa_requirements'=>'Standard visa requirements.','avg_monthly_cost_of_living'=>2400.00,'official_tax_authority_url'=>'https://www.canada.ca/en/revenue-agency.html','slug'=>'canada','meta_description'=>'Canada tax guide - federal and provincial rates, residency rules.','is_featured'=>false,'popularity_rank'=>17,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 18. Australia
            ['name'=>'Australia','iso_code'=>'AU','iso_code_3'=>'AUS','currency_code'=>'AUD','currency_symbol'=>'A$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-45%. Tax-free threshold A$18,200. Medicare levy 2%.','visa_requirements'=>'Standard visa requirements.','avg_monthly_cost_of_living'=>2800.00,'official_tax_authority_url'=>'https://www.ato.gov.au','slug'=>'australia','meta_description'=>'Australia tax guide - progressive rates, tax-free threshold, Medicare levy.','is_featured'=>false,'popularity_rank'=>18,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 19. South Korea
            ['name'=>'South Korea','iso_code'=>'KR','iso_code_3'=>'KOR','currency_code'=>'KRW','currency_symbol'=>'₩','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Workcation Visa','min_income_for_visa'=>2500.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 6%-45% + local 10% of national tax. Flat 19% option for foreign workers.','visa_requirements'=>'Digital nomad workcation visa available.','avg_monthly_cost_of_living'=>1800.00,'official_tax_authority_url'=>'https://www.nts.go.kr','slug'=>'south-korea','meta_description'=>'South Korea tax guide - progressive rates, workcation visa, expat flat rate.','is_featured'=>false,'popularity_rank'=>19,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 20. Brazil
            ['name'=>'Brazil','iso_code'=>'BR','iso_code_3'=>'BRA','currency_code'=>'BRL','currency_symbol'=>'R$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>1500.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-27.5%. 2026: income up to R$5,000/month exempt.','visa_requirements'=>'Proof of remote income, R$1,500/month.','avg_monthly_cost_of_living'=>900.00,'official_tax_authority_url'=>'https://www.gov.br/receitafederal','slug'=>'brazil','meta_description'=>'Brazil tax guide - progressive rates, digital nomad visa, 2026 exemption.','is_featured'=>false,'popularity_rank'=>20,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 21. Colombia
            ['name'=>'Colombia','iso_code'=>'CO','iso_code_3'=>'COL','currency_code'=>'COP','currency_symbol'=>'$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>684.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-39% (41% proposed 2026). Non-residents flat 35%.','visa_requirements'=>'3x minimum wage (~$684/month).','avg_monthly_cost_of_living'=>800.00,'official_tax_authority_url'=>'https://www.dian.gov.co','slug'=>'colombia','meta_description'=>'Colombia tax guide - progressive rates, digital nomad visa, low cost of living.','is_featured'=>false,'popularity_rank'=>21,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 22. Indonesia
            ['name'=>'Indonesia','iso_code'=>'ID','iso_code_3'=>'IDN','currency_code'=>'IDR','currency_symbol'=>'Rp','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'B211A Remote Worker Visa','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Progressive 5%-35%. Non-residents flat 20% withholding.','visa_requirements'=>'Proof of remote employment, $2,000/month.','avg_monthly_cost_of_living'=>800.00,'official_tax_authority_url'=>'https://www.pajak.go.id','slug'=>'indonesia','meta_description'=>'Indonesia tax guide - progressive rates, Bali digital nomad visa.','is_featured'=>false,'popularity_rank'=>22,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 23. Malaysia
            ['name'=>'Malaysia','iso_code'=>'MY','iso_code_3'=>'MYS','currency_code'=>'MYR','currency_symbol'=>'RM','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'DE Rantau Pass','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>182,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Progressive 0%-30%. Foreign-sourced income generally not taxed.','visa_requirements'=>'DE Rantau pass for digital professionals.','avg_monthly_cost_of_living'=>900.00,'official_tax_authority_url'=>'https://www.hasil.gov.my','slug'=>'malaysia','meta_description'=>'Malaysia tax guide - territorial taxation, DE Rantau, low rates.','is_featured'=>false,'popularity_rank'=>23,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 24. Czech Republic
            ['name'=>'Czech Republic','iso_code'=>'CZ','iso_code_3'=>'CZE','currency_code'=>'CZK','currency_symbol'=>'Kč','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Two rates: 15% up to CZK 1,762,812 then 23%.','visa_requirements'=>'Zivno visa for freelancers available.','avg_monthly_cost_of_living'=>1200.00,'official_tax_authority_url'=>'https://www.financnisprava.cz','slug'=>'czech-republic','meta_description'=>'Czech Republic tax guide - dual rate system, Zivno visa for freelancers.','is_featured'=>false,'popularity_rank'=>24,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 25. Hungary
            ['name'=>'Hungary','iso_code'=>'HU','iso_code_3'=>'HUN','currency_code'=>'HUF','currency_symbol'=>'Ft','has_progressive_tax'=>false,'flat_tax_rate'=>15.00,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'White Card','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Flat 15% PIT. Social contributions 18.5% (employee) + 13% (employer).','visa_requirements'=>'White Card for digital nomads.','avg_monthly_cost_of_living'=>1000.00,'official_tax_authority_url'=>'https://nav.gov.hu','slug'=>'hungary','meta_description'=>'Hungary tax guide - flat 15% rate, White Card digital nomad visa.','is_featured'=>false,'popularity_rank'=>25,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 26. Poland
            ['name'=>'Poland','iso_code'=>'PL','iso_code_3'=>'POL','currency_code'=>'PLN','currency_symbol'=>'zł','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'12% up to PLN 120,000 then 32%. Tax-free amount PLN 30,000.','visa_requirements'=>'Standard visa process.','avg_monthly_cost_of_living'=>1100.00,'official_tax_authority_url'=>'https://www.podatki.gov.pl','slug'=>'poland','meta_description'=>'Poland tax guide - dual rate system, tax-free threshold.','is_featured'=>false,'popularity_rank'=>26,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 27. Romania
            ['name'=>'Romania','iso_code'=>'RO','iso_code_3'=>'ROU','currency_code'=>'RON','currency_symbol'=>'lei','has_progressive_tax'=>false,'flat_tax_rate'=>10.00,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>3700.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Flat 10% income tax. Dividend tax increasing to 16% in 2026.','visa_requirements'=>'3x average gross salary.','avg_monthly_cost_of_living'=>800.00,'official_tax_authority_url'=>'https://www.anaf.ro','slug'=>'romania','meta_description'=>'Romania tax guide - flat 10% rate, digital nomad visa, low cost.','is_featured'=>false,'popularity_rank'=>27,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 28. Bulgaria
            ['name'=>'Bulgaria','iso_code'=>'BG','iso_code_3'=>'BGR','currency_code'=>'BGN','currency_symbol'=>'лв','has_progressive_tax'=>false,'flat_tax_rate'=>10.00,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Flat 10% income tax - one of the lowest in the EU.','visa_requirements'=>'Proof of remote work and income.','avg_monthly_cost_of_living'=>700.00,'official_tax_authority_url'=>'https://www.nra.bg','slug'=>'bulgaria','meta_description'=>'Bulgaria tax guide - flat 10% rate, lowest in the EU.','is_featured'=>false,'popularity_rank'=>28,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 29. Switzerland
            ['name'=>'Switzerland','iso_code'=>'CH','iso_code_3'=>'CHE','currency_code'=>'CHF','currency_symbol'=>'CHF','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Federal max 11.5%. Cantonal/municipal rates vary widely. Total can reach 40%+.','visa_requirements'=>'Work permit required.','avg_monthly_cost_of_living'=>3500.00,'official_tax_authority_url'=>'https://www.estv.admin.ch','slug'=>'switzerland','meta_description'=>'Switzerland tax guide - federal, cantonal, and municipal tax layers.','is_featured'=>false,'popularity_rank'=>29,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 30. Austria
            ['name'=>'Austria','iso_code'=>'AT','iso_code_3'=>'AUT','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-55%. Tax-free threshold €13,541. Six brackets.','visa_requirements'=>'Standard Austrian visa process.','avg_monthly_cost_of_living'=>1800.00,'official_tax_authority_url'=>'https://www.bmf.gv.at','slug'=>'austria','meta_description'=>'Austria tax guide - progressive rates up to 55%, six-bracket system.','is_featured'=>false,'popularity_rank'=>30,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 31. Ireland
            ['name'=>'Ireland','iso_code'=>'IE','iso_code_3'=>'IRL','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'20% standard up to €44,000, then 40%. USC 0.5%-8% applies. PRSI 4.35%.','visa_requirements'=>'Standard visa process.','avg_monthly_cost_of_living'=>2200.00,'official_tax_authority_url'=>'https://www.revenue.ie','slug'=>'ireland','meta_description'=>'Ireland tax guide - dual rates, USC, and PRSI contributions.','is_featured'=>false,'popularity_rank'=>31,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 32. Sweden
            ['name'=>'Sweden','iso_code'=>'SE','iso_code_3'=>'SWE','currency_code'=>'SEK','currency_symbol'=>'kr','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Municipal ~32.4% + state 20% above SEK 643,000. Capital gains 30% flat.','visa_requirements'=>'Work permit required.','avg_monthly_cost_of_living'=>2000.00,'official_tax_authority_url'=>'https://www.skatteverket.se','slug'=>'sweden','meta_description'=>'Sweden tax guide - municipal and state income tax rates.','is_featured'=>false,'popularity_rank'=>32,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 33. Costa Rica
            ['name'=>'Costa Rica','iso_code'=>'CR','iso_code_3'=>'CRI','currency_code'=>'CRC','currency_symbol'=>'₡','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>3000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Territorial taxation. DN visa holders exempt from tax on foreign income. Rates 10%-25%.','visa_requirements'=>'$3,000/month or $60,000/year income.','avg_monthly_cost_of_living'=>1200.00,'official_tax_authority_url'=>'https://www.hacienda.go.cr','slug'=>'costa-rica','meta_description'=>'Costa Rica tax guide - territorial taxation, digital nomad visa, tax exemption.','is_featured'=>false,'popularity_rank'=>33,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 34. Panama
            ['name'=>'Panama','iso_code'=>'PA','iso_code_3'=>'PAN','currency_code'=>'USD','currency_symbol'=>'$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Remote Worker Visa','min_income_for_visa'=>3000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Territorial taxation. Only Panama-source income taxed. Progressive 0%-25%.','visa_requirements'=>'$3,000/month minimum. No local employment.','avg_monthly_cost_of_living'=>1400.00,'official_tax_authority_url'=>'https://dgi.mef.gob.pa','slug'=>'panama','meta_description'=>'Panama tax guide - territorial system, zero tax on foreign income.','is_featured'=>false,'popularity_rank'=>34,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 35. Georgia
            ['name'=>'Georgia','iso_code'=>'GE','iso_code_3'=>'GEO','currency_code'=>'GEL','currency_symbol'=>'₾','has_progressive_tax'=>false,'flat_tax_rate'=>20.00,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Remotely from Georgia','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Flat 20% but territorial. Individual entrepreneurs: 1% on turnover up to 500k GEL.','visa_requirements'=>'$2,000/month, visa-free for many nationalities.','avg_monthly_cost_of_living'=>700.00,'official_tax_authority_url'=>'https://www.rs.ge','slug'=>'georgia','meta_description'=>'Georgia tax guide - 1% entrepreneur rate, territorial taxation.','is_featured'=>true,'popularity_rank'=>35,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 36. Malta
            ['name'=>'Malta','iso_code'=>'MT','iso_code_3'=>'MLT','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Nomad Residence Permit','min_income_for_visa'=>2700.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-35%. DN permit: 0% first year, then 10% on authorised work.','visa_requirements'=>'€2,700/month or €32,400/year.','avg_monthly_cost_of_living'=>1400.00,'official_tax_authority_url'=>'https://cfr.gov.mt','slug'=>'malta','meta_description'=>'Malta tax guide - nomad residence permit with special tax rate.','is_featured'=>false,'popularity_rank'=>36,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 37. Cyprus
            ['name'=>'Cyprus','iso_code'=>'CY','iso_code_3'=>'CYP','currency_code'=>'EUR','currency_symbol'=>'€','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>3500.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 0%-35%. Non-Dom regime: 0% on dividends, interest, and foreign income.','visa_requirements'=>'€3,500/month net income.','avg_monthly_cost_of_living'=>1300.00,'official_tax_authority_url'=>'https://www.tax.gov.cy','slug'=>'cyprus','meta_description'=>'Cyprus tax guide - Non-Dom regime, progressive rates, DN visa.','is_featured'=>false,'popularity_rank'=>37,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 38. Philippines
            ['name'=>'Philippines','iso_code'=>'PH','iso_code_3'=>'PHL','currency_code'=>'PHP','currency_symbol'=>'₱','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Digital Nomad Visa','min_income_for_visa'=>2000.00,'visa_income_period'=>'monthly','tax_residency_days'=>180,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Only Philippine-source income taxed. Progressive 0%-35%. DN visa: no local employment.','visa_requirements'=>'$2,000/month, no local clients.','avg_monthly_cost_of_living'=>700.00,'official_tax_authority_url'=>'https://www.bir.gov.ph','slug'=>'philippines','meta_description'=>'Philippines tax guide - territorial taxation, digital nomad visa.','is_featured'=>false,'popularity_rank'=>38,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 39. Vietnam
            ['name'=>'Vietnam','iso_code'=>'VN','iso_code_3'=>'VNM','currency_code'=>'VND','currency_symbol'=>'₫','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>true,'has_digital_nomad_visa'=>false,'digital_nomad_visa_name'=>null,'min_income_for_visa'=>null,'visa_income_period'=>null,'tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>true,'tax_system_notes'=>'Progressive 5%-35% for residents. Non-residents flat 20%. No DN visa yet.','visa_requirements'=>'Business visa or tourist visa.','avg_monthly_cost_of_living'=>600.00,'official_tax_authority_url'=>'https://www.gdt.gov.vn','slug'=>'vietnam','meta_description'=>'Vietnam tax guide - progressive rates, non-resident flat rate.','is_featured'=>false,'popularity_rank'=>39,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
            // 40. Barbados
            ['name'=>'Barbados','iso_code'=>'BB','iso_code_3'=>'BRB','currency_code'=>'BBD','currency_symbol'=>'Bds$','has_progressive_tax'=>true,'flat_tax_rate'=>null,'taxes_worldwide_income'=>false,'has_digital_nomad_visa'=>true,'digital_nomad_visa_name'=>'Welcome Stamp','min_income_for_visa'=>4166.00,'visa_income_period'=>'monthly','tax_residency_days'=>183,'counts_arrival_day'=>true,'counts_departure_day'=>false,'considers_center_of_vital_interests'=>false,'tax_system_notes'=>'Welcome Stamp holders: 0% tax on foreign income. Standard rates 12.5%-28.5%.','visa_requirements'=>'$50,000/year income. Valid for 12 months.','avg_monthly_cost_of_living'=>1600.00,'official_tax_authority_url'=>'https://www.bra.gov.bb','slug'=>'barbados','meta_description'=>'Barbados tax guide - Welcome Stamp with zero tax on foreign income.','is_featured'=>false,'popularity_rank'=>40,'is_active'=>true,'data_last_updated'=>2026,'created_at'=>$now,'updated_at'=>$now],
        ];

        DB::table('countries')->insert($countries);
    }
}
