<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DigitalNomadVisaSeeder extends Seeder
{
    public function run(): void
    {
        $visas = [
            // Portugal D7 Visa
            [
                'country_id' => 1,
                'visa_name' => 'D7 Passive Income Visa',
                'visa_type' => 'temporary_residence',
                'duration_months' => 12,
                'visa_cost' => 0,
                'min_monthly_income' => 1062.00,
                'min_annual_income' => 12744.00,
                'income_currency' => 'EUR',
                'income_source_requirements' => 'Passive income from investments, pensions, or rental income. No active work required.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 30,
                'additional_requirements' => 'Health insurance, proof of accommodation, background check.',
                'can_work_locally' => false,
                'can_bring_family' => true,
                'benefits_description' => 'Renewable annually. Gateway to Portuguese residency. Access to EU. NHR tax benefits available for first 10 years.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.sef.pt',
            ],

            // Spain Digital Nomad Visa
            [
                'country_id' => 2,
                'visa_name' => 'Spain Digital Nomad Visa',
                'visa_type' => 'temporary_residence',
                'duration_months' => 12,
                'visa_cost' => 70.00,
                'min_monthly_income' => 2300.00,
                'min_annual_income' => 27600.00,
                'income_currency' => 'EUR',
                'income_source_requirements' => 'Remote work for non-Spanish companies or self-employment with remote clients.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 20,
                'additional_requirements' => 'Health insurance required, employment contract or business proof, clean criminal record.',
                'can_work_locally' => false,
                'can_bring_family' => true,
                'benefits_description' => 'Renewable after 2 years. Fast-track to permanent residency after 3 years. EU access.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.inclusion.gob.es',
            ],

            // UK Tech Visa
            [
                'country_id' => 4,
                'visa_name' => 'UK Skilled Worker Visa',
                'visa_type' => 'temporary_residence',
                'duration_months' => 60,
                'visa_cost' => 719.00,
                'min_monthly_income' => 5000.00,
                'min_annual_income' => 60000.00,
                'income_currency' => 'GBP',
                'income_source_requirements' => 'Job offer from approved UK employer in skilled occupation.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 30,
                'additional_requirements' => 'Job sponsor, English language proficiency, tuberculosis test.',
                'can_work_locally' => true,
                'can_bring_family' => true,
                'benefits_description' => 'Path to Indefinite Leave to Remain (ILR) after 5 years. Access to UK public services.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.gov.uk/skilled-worker-visa',
            ],

            // Germany Freelance Visa
            [
                'country_id' => 5,
                'visa_name' => 'Germany Freelance Visa',
                'visa_type' => 'temporary_residence',
                'duration_months' => 24,
                'visa_cost' => 100.00,
                'min_monthly_income' => 1800.00,
                'min_annual_income' => 21600.00,
                'income_currency' => 'EUR',
                'income_source_requirements' => 'Freelance work or remote self-employment. Can serve clients internationally.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 45,
                'additional_requirements' => 'Health insurance, business plan, accommodation proof.',
                'can_work_locally' => true,
                'can_bring_family' => true,
                'benefits_description' => 'Renewable. Path to permanent residency. Full EU rights.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.make-it-in-germany.com',
            ],

            // Thailand Elite Visa
            [
                'country_id' => 7,
                'visa_name' => 'Thailand Elite Visa',
                'visa_type' => 'long_stay',
                'duration_months' => 120,
                'visa_cost' => 20000.00,
                'min_monthly_income' => 2000.00,
                'min_annual_income' => 24000.00,
                'income_currency' => 'USD',
                'income_source_requirements' => 'Investment in Thai Elite program. Remote income requirement varies by category.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 30,
                'additional_requirements' => 'Health insurance, criminal background check, strong financial standing.',
                'can_work_locally' => false,
                'can_bring_family' => true,
                'benefits_description' => '5-10 year validity. No extension hassles. Priority airport lane. Concierge services included.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.thailand-elite.com',
            ],

            // Thailand LTR Visa
            [
                'country_id' => 7,
                'visa_name' => 'Thailand Long Term Resident (LTR) Visa',
                'visa_type' => 'long_stay',
                'duration_months' => 120,
                'visa_cost' => 0,
                'min_monthly_income' => 2000.00,
                'min_annual_income' => 24000.00,
                'income_currency' => 'USD',
                'income_source_requirements' => 'Remote work, investment, or wealth criteria.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 60,
                'additional_requirements' => 'Proof of income, health insurance, background check.',
                'can_work_locally' => false,
                'can_bring_family' => true,
                'benefits_description' => '4-year initial term, renewable. Lower requirements than Elite. Government-endorsed.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.longtermresident.boi.go.th',
            ],

            // Mexico Temporal Visa
            [
                'country_id' => 8,
                'visa_name' => 'Mexico Temporal Residence Visa',
                'visa_type' => 'temporary_residence',
                'duration_months' => 48,
                'visa_cost' => 0,
                'min_monthly_income' => 2700.00,
                'min_annual_income' => 32400.00,
                'income_currency' => 'USD',
                'income_source_requirements' => 'Passive income, pension, savings. No employment required.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 30,
                'additional_requirements' => 'Bank proof, health insurance, clean record.',
                'can_work_locally' => false,
                'can_bring_family' => true,
                'benefits_description' => 'Renewable. Accessible cost of living. Gateway to permanent residency after 4 years.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://consulmex.sre.gob.mx',
            ],

            // UAE Virtual Working Program
            [
                'country_id' => 9,
                'visa_name' => 'UAE Virtual Working Program',
                'visa_type' => 'long_stay',
                'duration_months' => 12,
                'visa_cost' => 1200.00,
                'min_monthly_income' => 0,
                'min_annual_income' => 0,
                'income_currency' => 'AED',
                'income_source_requirements' => 'Any remote work. Freelancers and entrepreneurs eligible.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 15,
                'additional_requirements' => 'Work contract or self-employment proof, health insurance.',
                'can_work_locally' => false,
                'can_bring_family' => true,
                'benefits_description' => 'No income tax. Renewable. Access to UAE banking. Easy sponsorship process.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.virtualworking.ae',
            ],

            // UAE Golden Visa
            [
                'country_id' => 9,
                'visa_name' => 'UAE Golden Visa',
                'visa_type' => 'long_stay',
                'duration_months' => 360,
                'visa_cost' => 0,
                'min_monthly_income' => 0,
                'min_annual_income' => 0,
                'income_currency' => 'AED',
                'income_source_requirements' => 'Investment-based: real estate or business ownership',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 60,
                'additional_requirements' => 'Real estate purchase, business investment, or freelancer status.',
                'can_work_locally' => true,
                'can_bring_family' => true,
                'benefits_description' => '10-year renewable visa. No income tax. Can sponsor family. Permanent residency path.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.uaegoldenvisaservices.ae',
            ],

            // Singapore Tech Passes
            [
                'country_id' => 10,
                'visa_name' => 'Singapore Tech.Pass',
                'visa_type' => 'temporary_residence',
                'duration_months' => 36,
                'visa_cost' => 0,
                'min_monthly_income' => 12000.00,
                'min_annual_income' => 144000.00,
                'income_currency' => 'SGD',
                'income_source_requirements' => 'Tech industry expertise - startups, blockchain, AI, etc.',
                'min_stay_days' => 0,
                'max_stay_days' => null,
                'processing_days' => 14,
                'additional_requirements' => 'Tech credentials, startup founder status, or expert recognition.',
                'can_work_locally' => true,
                'can_bring_family' => false,
                'benefits_description' => 'Fast-tracked processing. Renewable. Path to permanent residency.',
                'available_from' => 2026,
                'is_active' => true,
                'official_url' => 'https://www.mom.gov.sg/passes-and-permits/tech-pass',
            ],
        ];

        DB::table('digital_nomad_visas')->insert($visas);
    }
}
