<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaxTreatySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // Helper to get country ID by ISO code
        $id = fn(string $iso) => DB::table('countries')->where('iso_code', $iso)->value('id');

        // Treaty pairs: [country_a, country_b, type (credit/exemption), description]
        $treaties = [
            // ── United States bilateral treaties ──────────────────────────────────
            ['US', 'GB', 'credit',      'US-UK Income Tax Treaty – Foreign tax credit method'],
            ['US', 'DE', 'credit',      'US-Germany Income Tax Treaty – Foreign tax credit method'],
            ['US', 'FR', 'credit',      'US-France Income Tax Treaty – Foreign tax credit method'],
            ['US', 'CA', 'credit',      'US-Canada Income Tax Treaty – Foreign tax credit method'],
            ['US', 'AU', 'credit',      'US-Australia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'JP', 'credit',      'US-Japan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'KR', 'credit',      'US-South Korea Income Tax Treaty – Foreign tax credit method'],
            ['US', 'ES', 'credit',      'US-Spain Income Tax Treaty – Foreign tax credit method'],
            ['US', 'IT', 'credit',      'US-Italy Income Tax Treaty – Foreign tax credit method'],
            ['US', 'NL', 'credit',      'US-Netherlands Income Tax Treaty – Foreign tax credit method'],
            ['US', 'CH', 'credit',      'US-Switzerland Income Tax Treaty – Foreign tax credit method'],
            ['US', 'IE', 'credit',      'US-Ireland Income Tax Treaty – Foreign tax credit method'],
            ['US', 'SE', 'credit',      'US-Sweden Income Tax Treaty – Foreign tax credit method'],
            ['US', 'AT', 'credit',      'US-Austria Income Tax Treaty – Foreign tax credit method'],
            ['US', 'TH', 'credit',      'US-Thailand Income Tax Treaty – Foreign tax credit method'],
            ['US', 'MX', 'credit',      'US-Mexico Income Tax Treaty – Foreign tax credit method'],
            ['US', 'PT', 'partial',     'US-Portugal Income Tax Treaty – Partial credit method'],
            ['US', 'CZ', 'credit',      'US-Czech Republic Income Tax Treaty – Foreign tax credit method'],
            ['US', 'HU', 'credit',      'US-Hungary Income Tax Treaty – Foreign tax credit method'],
            ['US', 'PL', 'credit',      'US-Poland Income Tax Treaty – Foreign tax credit method'],
            ['US', 'RO', 'credit',      'US-Romania Income Tax Treaty – Foreign tax credit method'],
            ['US', 'BG', 'credit',      'US-Bulgaria Income Tax Treaty – Foreign tax credit method'],
            ['US', 'CY', 'credit',      'US-Cyprus Income Tax Treaty – Foreign tax credit method'],
            ['US', 'EE', 'credit',      'US-Estonia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'PH', 'credit',      'US-Philippines Income Tax Treaty – Foreign tax credit method'],
            ['US', 'ID', 'credit',      'US-Indonesia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'BB', 'credit',      'US-Barbados Income Tax Treaty – Foreign tax credit method'],
            ['US', 'IN', 'credit',      'US-India Income Tax Treaty – Foreign tax credit method'],
            ['US', 'CN', 'credit',      'US-China Income Tax Treaty – Foreign tax credit method'],
            ['US', 'NZ', 'credit',      'US-New Zealand Income Tax Treaty – Foreign tax credit method'],
            ['US', 'NO', 'credit',      'US-Norway Income Tax Treaty – Foreign tax credit method'],
            ['US', 'DK', 'credit',      'US-Denmark Income Tax Treaty – Foreign tax credit method'],
            ['US', 'FI', 'credit',      'US-Finland Income Tax Treaty – Foreign tax credit method'],
            ['US', 'BE', 'credit',      'US-Belgium Income Tax Treaty – Foreign tax credit method'],
            ['US', 'IL', 'credit',      'US-Israel Income Tax Treaty – Foreign tax credit method'],
            ['US', 'ZA', 'credit',      'US-South Africa Income Tax Treaty – Foreign tax credit method'],
            ['US', 'CL', 'credit',      'US-Chile Income Tax Treaty – Foreign tax credit method'],
            ['US', 'AR', 'credit',      'US-Argentina Income Tax Treaty – Foreign tax credit method'],
            ['US', 'TR', 'credit',      'US-Turkey Income Tax Treaty – Foreign tax credit method'],
            ['US', 'GR', 'credit',      'US-Greece Income Tax Treaty – Foreign tax credit method'],
            ['US', 'SK', 'credit',      'US-Slovakia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'LT', 'credit',      'US-Lithuania Income Tax Treaty – Foreign tax credit method'],
            ['US', 'LV', 'credit',      'US-Latvia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'SI', 'credit',      'US-Slovenia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'HR', 'credit',      'US-Croatia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'UA', 'credit',      'US-Ukraine Income Tax Treaty – Foreign tax credit method'],
            ['US', 'RU', 'credit',      'US-Russia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'KZ', 'credit',      'US-Kazakhstan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'UZ', 'credit',      'US-Uzbekistan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'AM', 'credit',      'US-Armenia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'GE', 'credit',      'US-Georgia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'AZ', 'credit',      'US-Azerbaijan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'BY', 'credit',      'US-Belarus Income Tax Treaty – Foreign tax credit method'],
            ['US', 'KG', 'credit',      'US-Kyrgyzstan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'TM', 'credit',      'US-Turkmenistan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'TJ', 'credit',      'US-Tajikistan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'MD', 'credit',      'US-Moldova Income Tax Treaty – Foreign tax credit method'],
            ['US', 'EG', 'credit',      'US-Egypt Income Tax Treaty – Foreign tax credit method'],
            ['US', 'MA', 'credit',      'US-Morocco Income Tax Treaty – Foreign tax credit method'],
            ['US', 'TN', 'credit',      'US-Tunisia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'PK', 'credit',      'US-Pakistan Income Tax Treaty – Foreign tax credit method'],
            ['US', 'BD', 'credit',      'US-Bangladesh Income Tax Treaty – Foreign tax credit method'],
            ['US', 'SG', 'credit',      'US-Singapore Income Tax Treaty – Foreign tax credit method'],
            ['US', 'MY', 'credit',      'US-Malaysia Income Tax Treaty – Foreign tax credit method'],
            ['US', 'VE', 'credit',      'US-Venezuela Income Tax Treaty – Foreign tax credit method'],
            ['US', 'CO', 'credit',      'US-Colombia Income Tax Treaty – Foreign tax credit method'],

            // ── UK bilateral treaties ──────────────────────────────────────────────
            ['GB', 'DE', 'credit',      'UK-Germany Double Taxation Convention – Credit method'],
            ['GB', 'FR', 'credit',      'UK-France Double Taxation Convention – Credit method'],
            ['GB', 'ES', 'credit',      'UK-Spain Double Taxation Convention – Credit method'],
            ['GB', 'IT', 'credit',      'UK-Italy Double Taxation Convention – Credit method'],
            ['GB', 'PT', 'credit',      'UK-Portugal Double Taxation Convention – Credit method'],
            ['GB', 'NL', 'credit',      'UK-Netherlands Double Taxation Convention – Credit method'],
            ['GB', 'IE', 'credit',      'UK-Ireland Double Taxation Convention – Credit method'],
            ['GB', 'AU', 'credit',      'UK-Australia Double Taxation Convention – Credit method'],
            ['GB', 'CA', 'credit',      'UK-Canada Double Taxation Convention – Credit method'],
            ['GB', 'JP', 'credit',      'UK-Japan Double Taxation Convention – Credit method'],
            ['GB', 'SG', 'credit',      'UK-Singapore Double Taxation Convention – Credit method'],
            ['GB', 'AE', 'exemption',   'UK-UAE Double Taxation Convention – Exemption method'],
            ['GB', 'MT', 'credit',      'UK-Malta Double Taxation Convention – Credit method'],
            ['GB', 'CY', 'credit',      'UK-Cyprus Double Taxation Convention – Credit method'],
            ['GB', 'IN', 'credit',      'UK-India Double Taxation Convention – Credit method'],
            ['GB', 'CN', 'credit',      'UK-China Double Taxation Convention – Credit method'],
            ['GB', 'HK', 'exemption',   'UK-Hong Kong Double Taxation Convention – Exemption method'],
            ['GB', 'SA', 'exemption',   'UK-Saudi Arabia Double Taxation Convention – Exemption method'],
            ['GB', 'TR', 'credit',      'UK-Turkey Double Taxation Convention – Credit method'],
            ['GB', 'NO', 'credit',      'UK-Norway Double Taxation Convention – Credit method'],
            ['GB', 'DK', 'credit',      'UK-Denmark Double Taxation Convention – Credit method'],
            ['GB', 'FI', 'credit',      'UK-Finland Double Taxation Convention – Credit method'],
            ['GB', 'BE', 'credit',      'UK-Belgium Double Taxation Convention – Credit method'],
            ['GB', 'IL', 'credit',      'UK-Israel Double Taxation Convention – Credit method'],
            ['GB', 'ZA', 'credit',      'UK-South Africa Double Taxation Convention – Credit method'],
            ['GB', 'NZ', 'credit',      'UK-New Zealand Double Taxation Convention – Credit method'],
            ['GB', 'KR', 'credit',      'UK-South Korea Double Taxation Convention – Credit method'],
            ['GB', 'RU', 'credit',      'UK-Russia Double Taxation Convention – Credit method'],
            ['GB', 'PL', 'credit',      'UK-Poland Double Taxation Convention – Credit method'],
            ['GB', 'SE', 'credit',      'UK-Sweden Double Taxation Convention – Credit method'],
            ['GB', 'AT', 'credit',      'UK-Austria Double Taxation Convention – Credit method'],
            ['GB', 'CH', 'credit',      'UK-Switzerland Double Taxation Convention – Credit method'],
            ['GB', 'GR', 'credit',      'UK-Greece Double Taxation Convention – Credit method'],
            ['GB', 'PK', 'credit',      'UK-Pakistan Double Taxation Convention – Credit method'],
            ['GB', 'EG', 'credit',      'UK-Egypt Double Taxation Convention – Credit method'],
            ['GB', 'NG', 'credit',      'UK-Nigeria Double Taxation Convention – Credit method'],
            ['GB', 'KE', 'credit',      'UK-Kenya Double Taxation Convention – Credit method'],
            ['GB', 'ZW', 'credit',      'UK-Zimbabwe Double Taxation Convention – Credit method'],
            ['GB', 'GH', 'credit',      'UK-Ghana Double Taxation Convention – Credit method'],
            ['GB', 'MY', 'credit',      'UK-Malaysia Double Taxation Convention – Credit method'],
            ['GB', 'TH', 'credit',      'UK-Thailand Double Taxation Convention – Credit method'],
            ['GB', 'VN', 'credit',      'UK-Vietnam Double Taxation Convention – Credit method'],

            // ── Major EU/European cross-treaties ──────────────────────────────────
            ['DE', 'FR', 'credit',      'Germany-France DTA – Credit method'],
            ['DE', 'ES', 'credit',      'Germany-Spain DTA – Credit method'],
            ['DE', 'IT', 'credit',      'Germany-Italy DTA – Credit method'],
            ['DE', 'NL', 'credit',      'Germany-Netherlands DTA – Credit method'],
            ['DE', 'AT', 'credit',      'Germany-Austria DTA – Credit method'],
            ['DE', 'CH', 'credit',      'Germany-Switzerland DTA – Credit method'],
            ['DE', 'PT', 'credit',      'Germany-Portugal DTA – Credit method'],
            ['DE', 'SE', 'credit',      'Germany-Sweden DTA – Credit method'],
            ['DE', 'DK', 'credit',      'Germany-Denmark DTA – Credit method'],
            ['DE', 'NO', 'credit',      'Germany-Norway DTA – Credit method'],
            ['DE', 'FI', 'credit',      'Germany-Finland DTA – Credit method'],
            ['DE', 'BE', 'credit',      'Germany-Belgium DTA – Credit method'],
            ['DE', 'LU', 'credit',      'Germany-Luxembourg DTA – Credit method'],
            ['DE', 'PL', 'credit',      'Germany-Poland DTA – Credit method'],
            ['DE', 'CZ', 'credit',      'Germany-Czech Republic DTA – Credit method'],
            ['DE', 'SK', 'credit',      'Germany-Slovakia DTA – Credit method'],
            ['DE', 'HU', 'credit',      'Germany-Hungary DTA – Credit method'],
            ['DE', 'RO', 'credit',      'Germany-Romania DTA – Credit method'],
            ['DE', 'BG', 'credit',      'Germany-Bulgaria DTA – Credit method'],
            ['DE', 'GR', 'credit',      'Germany-Greece DTA – Credit method'],
            ['DE', 'HR', 'credit',      'Croatia-Germany DTA – Credit method'],
            ['DE', 'EE', 'credit',      'Estonia-Germany DTA – Credit method'],
            ['DE', 'LV', 'credit',      'Latvia-Germany DTA – Credit method'],
            ['DE', 'LT', 'credit',      'Lithuania-Germany DTA – Credit method'],
            ['DE', 'SI', 'credit',      'Slovenia-Germany DTA – Credit method'],
            ['DE', 'IE', 'credit',      'Germany-Ireland DTA – Credit method'],
            ['DE', 'TR', 'credit',      'Germany-Turkey DTA – Credit method'],
            ['DE', 'RU', 'credit',      'Germany-Russia DTA – Credit method'],
            ['DE', 'UA', 'credit',      'Germany-Ukraine DTA – Credit method'],
            ['DE', 'IL', 'credit',      'Germany-Israel DTA – Credit method'],
            ['DE', 'IN', 'credit',      'Germany-India DTA – Credit method'],
            ['DE', 'CN', 'credit',      'Germany-China DTA – Credit method'],
            ['DE', 'JP', 'credit',      'Germany-Japan DTA – Credit method'],
            ['DE', 'KR', 'credit',      'Germany-South Korea DTA – Credit method'],
            ['DE', 'SG', 'credit',      'Germany-Singapore DTA – Credit method'],
            ['DE', 'AU', 'credit',      'Germany-Australia DTA – Credit method'],
            ['DE', 'NZ', 'credit',      'Germany-New Zealand DTA – Credit method'],
            ['DE', 'ZA', 'credit',      'Germany-South Africa DTA – Credit method'],
            ['DE', 'EG', 'credit',      'Germany-Egypt DTA – Credit method'],
            ['DE', 'MA', 'credit',      'Germany-Morocco DTA – Credit method'],
            ['DE', 'GE', 'credit',      'Georgia-Germany DTA – Credit method'],

            // ── France bilateral treaties ──────────────────────────────────────────
            ['FR', 'ES', 'credit',      'France-Spain DTA – Credit method'],
            ['FR', 'IT', 'credit',      'France-Italy DTA – Credit method'],
            ['FR', 'PT', 'credit',      'France-Portugal DTA – Credit method'],
            ['FR', 'NL', 'credit',      'France-Netherlands DTA – Credit method'],
            ['FR', 'BE', 'credit',      'France-Belgium DTA – Credit method'],
            ['FR', 'LU', 'credit',      'France-Luxembourg DTA – Credit method'],
            ['FR', 'CH', 'credit',      'France-Switzerland DTA – Credit method'],
            ['FR', 'AT', 'credit',      'France-Austria DTA – Credit method'],
            ['FR', 'SE', 'credit',      'France-Sweden DTA – Credit method'],
            ['FR', 'DK', 'credit',      'France-Denmark DTA – Credit method'],
            ['FR', 'NO', 'credit',      'France-Norway DTA – Credit method'],
            ['FR', 'FI', 'credit',      'France-Finland DTA – Credit method'],
            ['FR', 'PL', 'credit',      'France-Poland DTA – Credit method'],
            ['FR', 'CZ', 'credit',      'France-Czech Republic DTA – Credit method'],
            ['FR', 'HU', 'credit',      'France-Hungary DTA – Credit method'],
            ['FR', 'RO', 'credit',      'France-Romania DTA – Credit method'],
            ['FR', 'BG', 'credit',      'France-Bulgaria DTA – Credit method'],
            ['FR', 'GR', 'credit',      'France-Greece DTA – Credit method'],
            ['FR', 'TR', 'credit',      'France-Turkey DTA – Credit method'],
            ['FR', 'RU', 'credit',      'France-Russia DTA – Credit method'],
            ['FR', 'UA', 'credit',      'France-Ukraine DTA – Credit method'],
            ['FR', 'IL', 'credit',      'France-Israel DTA – Credit method'],
            ['FR', 'IN', 'credit',      'France-India DTA – Credit method'],
            ['FR', 'CN', 'credit',      'France-China DTA – Credit method'],
            ['FR', 'JP', 'credit',      'France-Japan DTA – Credit method'],
            ['FR', 'KR', 'credit',      'France-South Korea DTA – Credit method'],
            ['FR', 'SG', 'credit',      'France-Singapore DTA – Credit method'],
            ['FR', 'AU', 'credit',      'France-Australia DTA – Credit method'],
            ['FR', 'NZ', 'credit',      'France-New Zealand DTA – Credit method'],
            ['FR', 'ZA', 'credit',      'France-South Africa DTA – Credit method'],
            ['FR', 'MA', 'credit',      'France-Morocco DTA – Credit method'],
            ['FR', 'TN', 'credit',      'France-Tunisia DTA – Credit method'],
            ['FR', 'DZ', 'credit',      'France-Algeria DTA – Credit method'],
            ['FR', 'EG', 'credit',      'France-Egypt DTA – Credit method'],
            ['FR', 'SA', 'credit',      'France-Saudi Arabia DTA – Credit method'],
            ['FR', 'AE', 'exemption',   'France-UAE DTA – Exemption method'],
            ['FR', 'HK', 'credit',      'France-Hong Kong DTA – Credit method'],
            ['FR', 'MX', 'credit',      'France-Mexico DTA – Credit method'],
            ['FR', 'BR', 'credit',      'France-Brazil DTA – Credit method'],
            ['FR', 'CA', 'credit',      'France-Canada DTA – Credit method'],

            // ── Italy bilateral treaties ───────────────────────────────────────────
            ['IT', 'ES', 'credit',      'Italy-Spain DTA – Credit method'],
            ['IT', 'PT', 'credit',      'Italy-Portugal DTA – Credit method'],
            ['IT', 'NL', 'credit',      'Italy-Netherlands DTA – Credit method'],
            ['IT', 'BE', 'credit',      'Italy-Belgium DTA – Credit method'],
            ['IT', 'LU', 'credit',      'Italy-Luxembourg DTA – Credit method'],
            ['IT', 'CH', 'credit',      'Italy-Switzerland DTA – Credit method'],
            ['IT', 'AT', 'credit',      'Italy-Austria DTA – Credit method'],
            ['IT', 'SE', 'credit',      'Italy-Sweden DTA – Credit method'],
            ['IT', 'DK', 'credit',      'Italy-Denmark DTA – Credit method'],
            ['IT', 'NO', 'credit',      'Italy-Norway DTA – Credit method'],
            ['IT', 'FI', 'credit',      'Italy-Finland DTA – Credit method'],
            ['IT', 'GR', 'credit',      'Italy-Greece DTA – Credit method'],
            ['IT', 'PL', 'credit',      'Italy-Poland DTA – Credit method'],
            ['IT', 'HU', 'credit',      'Italy-Hungary DTA – Credit method'],
            ['IT', 'RO', 'credit',      'Italy-Romania DTA – Credit method'],
            ['IT', 'BG', 'credit',      'Italy-Bulgaria DTA – Credit method'],
            ['IT', 'CZ', 'credit',      'Italy-Czech Republic DTA – Credit method'],
            ['IT', 'HR', 'credit',      'Italy-Croatia DTA – Credit method'],
            ['IT', 'SI', 'credit',      'Italy-Slovenia DTA – Credit method'],
            ['IT', 'TR', 'credit',      'Italy-Turkey DTA – Credit method'],
            ['IT', 'RU', 'credit',      'Italy-Russia DTA – Credit method'],
            ['IT', 'UA', 'credit',      'Italy-Ukraine DTA – Credit method'],
            ['IT', 'IL', 'credit',      'Italy-Israel DTA – Credit method'],
            ['IT', 'IN', 'credit',      'Italy-India DTA – Credit method'],
            ['IT', 'CN', 'credit',      'Italy-China DTA – Credit method'],
            ['IT', 'JP', 'credit',      'Italy-Japan DTA – Credit method'],
            ['IT', 'KR', 'credit',      'Italy-South Korea DTA – Credit method'],
            ['IT', 'SG', 'credit',      'Italy-Singapore DTA – Credit method'],
            ['IT', 'AU', 'credit',      'Italy-Australia DTA – Credit method'],
            ['IT', 'EG', 'credit',      'Italy-Egypt DTA – Credit method'],
            ['IT', 'MA', 'credit',      'Italy-Morocco DTA – Credit method'],
            ['IT', 'AE', 'exemption',   'Italy-UAE DTA – Exemption method'],
            ['IT', 'BR', 'credit',      'Italy-Brazil DTA – Credit method'],
            ['IT', 'MX', 'credit',      'Italy-Mexico DTA – Credit method'],
            ['IT', 'CA', 'credit',      'Italy-Canada DTA – Credit method'],

            // ── Spain bilateral treaties ───────────────────────────────────────────
            ['ES', 'PT', 'credit',      'Spain-Portugal DTA – Credit method'],
            ['ES', 'NL', 'credit',      'Spain-Netherlands DTA – Credit method'],
            ['ES', 'BE', 'credit',      'Spain-Belgium DTA – Credit method'],
            ['ES', 'CH', 'credit',      'Spain-Switzerland DTA – Credit method'],
            ['ES', 'AT', 'credit',      'Spain-Austria DTA – Credit method'],
            ['ES', 'SE', 'credit',      'Spain-Sweden DTA – Credit method'],
            ['ES', 'DK', 'credit',      'Spain-Denmark DTA – Credit method'],
            ['ES', 'NO', 'credit',      'Spain-Norway DTA – Credit method'],
            ['ES', 'FI', 'credit',      'Spain-Finland DTA – Credit method'],
            ['ES', 'GR', 'credit',      'Spain-Greece DTA – Credit method'],
            ['ES', 'PL', 'credit',      'Spain-Poland DTA – Credit method'],
            ['ES', 'HU', 'credit',      'Spain-Hungary DTA – Credit method'],
            ['ES', 'RO', 'credit',      'Spain-Romania DTA – Credit method'],
            ['ES', 'BG', 'credit',      'Spain-Bulgaria DTA – Credit method'],
            ['ES', 'CZ', 'credit',      'Spain-Czech Republic DTA – Credit method'],
            ['ES', 'TR', 'credit',      'Spain-Turkey DTA – Credit method'],
            ['ES', 'RU', 'credit',      'Spain-Russia DTA – Credit method'],
            ['ES', 'IL', 'credit',      'Spain-Israel DTA – Credit method'],
            ['ES', 'IN', 'credit',      'Spain-India DTA – Credit method'],
            ['ES', 'CN', 'credit',      'Spain-China DTA – Credit method'],
            ['ES', 'JP', 'credit',      'Spain-Japan DTA – Credit method'],
            ['ES', 'KR', 'credit',      'Spain-South Korea DTA – Credit method'],
            ['ES', 'SG', 'credit',      'Spain-Singapore DTA – Credit method'],
            ['ES', 'AU', 'credit',      'Spain-Australia DTA – Credit method'],
            ['ES', 'NZ', 'credit',      'Spain-New Zealand DTA – Credit method'],
            ['ES', 'ZA', 'credit',      'Spain-South Africa DTA – Credit method'],
            ['ES', 'MA', 'credit',      'Spain-Morocco DTA – Credit method'],
            ['ES', 'MX', 'credit',      'Mexico-Spain DTA – Credit method'],
            ['ES', 'BR', 'credit',      'Spain-Brazil DTA – Credit method'],
            ['ES', 'AR', 'credit',      'Argentina-Spain DTA – Credit method'],
            ['ES', 'CL', 'credit',      'Chile-Spain DTA – Credit method'],
            ['ES', 'CO', 'credit',      'Spain-Colombia DTA – Credit method'],
            ['ES', 'PE', 'credit',      'Spain-Peru DTA – Credit method'],
            ['ES', 'CA', 'credit',      'Spain-Canada DTA – Credit method'],
            ['ES', 'AE', 'exemption',   'Spain-UAE DTA – Exemption method'],
            ['ES', 'CR', 'credit',      'Costa Rica-Spain DTA – Credit method'],

            // ── Nordic cross-treaties ──────────────────────────────────────────────
            ['SE', 'NO', 'credit',      'Sweden-Norway DTA – Nordic Convention'],
            ['SE', 'DK', 'credit',      'Sweden-Denmark DTA – Nordic Convention'],
            ['SE', 'FI', 'credit',      'Sweden-Finland DTA – Nordic Convention'],
            ['SE', 'IS', 'credit',      'Sweden-Iceland DTA – Nordic Convention'],
            ['NO', 'DK', 'credit',      'Norway-Denmark DTA – Nordic Convention'],
            ['NO', 'FI', 'credit',      'Norway-Finland DTA – Nordic Convention'],
            ['NO', 'IS', 'credit',      'Norway-Iceland DTA – Nordic Convention'],
            ['DK', 'FI', 'credit',      'Denmark-Finland DTA – Nordic Convention'],
            ['DK', 'IS', 'credit',      'Denmark-Iceland DTA – Nordic Convention'],
            ['FI', 'IS', 'credit',      'Finland-Iceland DTA – Nordic Convention'],
            ['SE', 'NL', 'credit',      'Sweden-Netherlands DTA – Credit method'],
            ['SE', 'BE', 'credit',      'Sweden-Belgium DTA – Credit method'],
            ['SE', 'CH', 'credit',      'Sweden-Switzerland DTA – Credit method'],
            ['SE', 'AT', 'credit',      'Sweden-Austria DTA – Credit method'],
            ['SE', 'IL', 'credit',      'Sweden-Israel DTA – Credit method'],
            ['SE', 'JP', 'credit',      'Sweden-Japan DTA – Credit method'],
            ['SE', 'CN', 'credit',      'Sweden-China DTA – Credit method'],
            ['SE', 'KR', 'credit',      'Sweden-South Korea DTA – Credit method'],
            ['SE', 'SG', 'credit',      'Sweden-Singapore DTA – Credit method'],
            ['SE', 'AU', 'credit',      'Sweden-Australia DTA – Credit method'],
            ['NO', 'NL', 'credit',      'Norway-Netherlands DTA – Credit method'],
            ['NO', 'BE', 'credit',      'Norway-Belgium DTA – Credit method'],
            ['NO', 'CH', 'credit',      'Norway-Switzerland DTA – Credit method'],
            ['NO', 'IN', 'credit',      'Norway-India DTA – Credit method'],
            ['DK', 'NL', 'credit',      'Denmark-Netherlands DTA – Credit method'],
            ['DK', 'BE', 'credit',      'Denmark-Belgium DTA – Credit method'],
            ['DK', 'CH', 'credit',      'Denmark-Switzerland DTA – Credit method'],
            ['DK', 'IN', 'credit',      'Denmark-India DTA – Credit method'],
            ['FI', 'NL', 'credit',      'Finland-Netherlands DTA – Credit method'],
            ['FI', 'BE', 'credit',      'Finland-Belgium DTA – Credit method'],
            ['FI', 'CH', 'credit',      'Finland-Switzerland DTA – Credit method'],
            ['FI', 'JP', 'credit',      'Finland-Japan DTA – Credit method'],
            ['FI', 'CN', 'credit',      'Finland-China DTA – Credit method'],

            // ── Benelux cross-treaties ─────────────────────────────────────────────
            ['NL', 'BE', 'credit',      'Netherlands-Belgium DTA – Credit method'],
            ['NL', 'LU', 'credit',      'Netherlands-Luxembourg DTA – Credit method'],
            ['BE', 'LU', 'credit',      'Belgium-Luxembourg DTA – Credit method'],
            ['NL', 'CH', 'credit',      'Netherlands-Switzerland DTA – Credit method'],
            ['NL', 'AT', 'credit',      'Netherlands-Austria DTA – Credit method'],
            ['NL', 'JP', 'credit',      'Netherlands-Japan DTA – Credit method'],
            ['NL', 'CN', 'credit',      'Netherlands-China DTA – Credit method'],
            ['NL', 'KR', 'credit',      'Netherlands-South Korea DTA – Credit method'],
            ['NL', 'SG', 'credit',      'Netherlands-Singapore DTA – Credit method'],
            ['NL', 'AU', 'credit',      'Netherlands-Australia DTA – Credit method'],
            ['NL', 'IN', 'credit',      'Netherlands-India DTA – Credit method'],
            ['NL', 'ZA', 'credit',      'Netherlands-South Africa DTA – Credit method'],
            ['NL', 'AE', 'exemption',   'Netherlands-UAE DTA – Exemption method'],
            ['NL', 'IL', 'credit',      'Netherlands-Israel DTA – Credit method'],
            ['NL', 'TR', 'credit',      'Netherlands-Turkey DTA – Credit method'],
            ['NL', 'RU', 'credit',      'Netherlands-Russia DTA – Credit method'],
            ['NL', 'MX', 'credit',      'Netherlands-Mexico DTA – Credit method'],
            ['NL', 'BR', 'credit',      'Netherlands-Brazil DTA – Credit method'],
            ['BE', 'CH', 'credit',      'Belgium-Switzerland DTA – Credit method'],
            ['BE', 'JP', 'credit',      'Belgium-Japan DTA – Credit method'],
            ['BE', 'CN', 'credit',      'Belgium-China DTA – Credit method'],
            ['BE', 'KR', 'credit',      'Belgium-South Korea DTA – Credit method'],
            ['BE', 'IN', 'credit',      'Belgium-India DTA – Credit method'],
            ['BE', 'AU', 'credit',      'Belgium-Australia DTA – Credit method'],
            ['BE', 'TR', 'credit',      'Belgium-Turkey DTA – Credit method'],

            // ── Switzerland & Austria cross-treaties ───────────────────────────────
            ['CH', 'AT', 'credit',      'Switzerland-Austria DTA – Credit method'],
            ['CH', 'JP', 'credit',      'Switzerland-Japan DTA – Credit method'],
            ['CH', 'CN', 'credit',      'Switzerland-China DTA – Credit method'],
            ['CH', 'KR', 'credit',      'Switzerland-South Korea DTA – Credit method'],
            ['CH', 'SG', 'credit',      'Switzerland-Singapore DTA – Credit method'],
            ['CH', 'AU', 'credit',      'Switzerland-Australia DTA – Credit method'],
            ['CH', 'IN', 'credit',      'Switzerland-India DTA – Credit method'],
            ['CH', 'ZA', 'credit',      'Switzerland-South Africa DTA – Credit method'],
            ['CH', 'AE', 'exemption',   'Switzerland-UAE DTA – Exemption method'],
            ['CH', 'IL', 'credit',      'Switzerland-Israel DTA – Credit method'],
            ['CH', 'TR', 'credit',      'Switzerland-Turkey DTA – Credit method'],
            ['CH', 'RU', 'credit',      'Switzerland-Russia DTA – Credit method'],
            ['CH', 'SA', 'exemption',   'Switzerland-Saudi Arabia DTA – Exemption method'],
            ['CH', 'MX', 'credit',      'Switzerland-Mexico DTA – Credit method'],
            ['AT', 'JP', 'credit',      'Austria-Japan DTA – Credit method'],
            ['AT', 'CN', 'credit',      'Austria-China DTA – Credit method'],
            ['AT', 'KR', 'credit',      'Austria-South Korea DTA – Credit method'],
            ['AT', 'IN', 'credit',      'Austria-India DTA – Credit method'],
            ['AT', 'AU', 'credit',      'Austria-Australia DTA – Credit method'],
            ['AT', 'RU', 'credit',      'Austria-Russia DTA – Credit method'],
            ['AT', 'AE', 'exemption',   'Austria-UAE DTA – Exemption method'],
            // ── Singapore bilateral treaties ──────────────────────────────────────
            ['SG', 'AU', 'exemption',   'Singapore-Australia DTA – Exemption with progression'],
            ['SG', 'JP', 'credit',      'Singapore-Japan DTA – Foreign tax credit method'],
            ['SG', 'KR', 'credit',      'Singapore-South Korea DTA – Foreign tax credit method'],
            ['SG', 'TH', 'credit',      'Singapore-Thailand DTA – Foreign tax credit method'],
            ['SG', 'MY', 'exemption',   'Singapore-Malaysia DTA – Exemption method'],
            ['SG', 'ID', 'credit',      'Singapore-Indonesia DTA – Foreign tax credit method'],
            ['SG', 'VN', 'credit',      'Singapore-Vietnam DTA – Foreign tax credit method'],
            ['SG', 'PH', 'credit',      'Singapore-Philippines DTA – Foreign tax credit method'],
            ['SG', 'IN', 'credit',      'India-Singapore DTA – Foreign tax credit method'],
            ['SG', 'CN', 'credit',      'China-Singapore DTA – Foreign tax credit method'],
            ['SG', 'HK', 'exemption',   'Hong Kong-Singapore DTA – Exemption method'],
            ['SG', 'NZ', 'credit',      'New Zealand-Singapore DTA – Credit method'],
            ['SG', 'AE', 'exemption',   'Singapore-UAE DTA – Exemption method'],
            ['SG', 'SA', 'exemption',   'Saudi Arabia-Singapore DTA – Exemption method'],
            ['SG', 'IL', 'credit',      'Singapore-Israel DTA – Credit method'],
            ['SG', 'ZA', 'credit',      'Singapore-South Africa DTA – Credit method'],
            ['SG', 'RU', 'credit',      'Singapore-Russia DTA – Credit method'],
            ['SG', 'MX', 'credit',      'Singapore-Mexico DTA – Credit method'],
            ['SG', 'BR', 'credit',      'Singapore-Brazil DTA – Credit method'],
            ['SG', 'LK', 'credit',      'Singapore-Sri Lanka DTA – Credit method'],
            ['SG', 'PK', 'credit',      'Singapore-Pakistan DTA – Credit method'],
            ['SG', 'BD', 'credit',      'Singapore-Bangladesh DTA – Credit method'],
            ['SG', 'MM', 'credit',      'Singapore-Myanmar DTA – Credit method'],
            ['SG', 'KH', 'credit',      'Singapore-Cambodia DTA – Credit method'],

            // ── Japan bilateral treaties ───────────────────────────────────────────
            ['JP', 'AU', 'credit',      'Japan-Australia DTA – Foreign tax credit method'],
            ['JP', 'KR', 'credit',      'Japan-South Korea DTA – Foreign tax credit method'],
            ['JP', 'TH', 'credit',      'Japan-Thailand DTA – Foreign tax credit method'],
            ['JP', 'CN', 'credit',      'Japan-China DTA – Foreign tax credit method'],
            ['JP', 'IN', 'credit',      'Japan-India DTA – Foreign tax credit method'],
            ['JP', 'HK', 'credit',      'Japan-Hong Kong DTA – Credit method'],
            ['JP', 'MY', 'credit',      'Japan-Malaysia DTA – Credit method'],
            ['JP', 'ID', 'credit',      'Japan-Indonesia DTA – Credit method'],
            ['JP', 'PH', 'credit',      'Japan-Philippines DTA – Credit method'],
            ['JP', 'VN', 'credit',      'Japan-Vietnam DTA – Credit method'],
            ['JP', 'NZ', 'credit',      'Japan-New Zealand DTA – Credit method'],
            ['JP', 'ZA', 'credit',      'Japan-South Africa DTA – Credit method'],
            ['JP', 'AE', 'exemption',   'Japan-UAE DTA – Exemption method'],
            ['JP', 'SA', 'exemption',   'Japan-Saudi Arabia DTA – Exemption method'],
            ['JP', 'IL', 'credit',      'Japan-Israel DTA – Credit method'],
            ['JP', 'TR', 'credit',      'Japan-Turkey DTA – Credit method'],
            ['JP', 'RU', 'credit',      'Japan-Russia DTA – Credit method'],
            ['JP', 'MX', 'credit',      'Japan-Mexico DTA – Credit method'],
            ['JP', 'BR', 'credit',      'Japan-Brazil DTA – Credit method'],
            ['JP', 'CA', 'credit',      'Japan-Canada DTA – Credit method'],
            ['JP', 'PL', 'credit',      'Japan-Poland DTA – Credit method'],
            ['JP', 'CZ', 'credit',      'Japan-Czech Republic DTA – Credit method'],
            ['JP', 'HU', 'credit',      'Japan-Hungary DTA – Credit method'],
            ['JP', 'RO', 'credit',      'Japan-Romania DTA – Credit method'],
            ['JP', 'PK', 'credit',      'Japan-Pakistan DTA – Credit method'],
            ['JP', 'BD', 'credit',      'Japan-Bangladesh DTA – Credit method'],
            ['JP', 'LK', 'credit',      'Japan-Sri Lanka DTA – Credit method'],
            ['JP', 'EG', 'credit',      'Japan-Egypt DTA – Credit method'],

            // ── South Korea bilateral treaties ─────────────────────────────────────
            ['KR', 'AU', 'credit',      'South Korea-Australia DTA – Credit method'],
            ['KR', 'CN', 'credit',      'China-South Korea DTA – Credit method'],
            ['KR', 'IN', 'credit',      'South Korea-India DTA – Credit method'],
            ['KR', 'HK', 'credit',      'South Korea-Hong Kong DTA – Credit method'],
            ['KR', 'MY', 'credit',      'South Korea-Malaysia DTA – Credit method'],
            ['KR', 'ID', 'credit',      'South Korea-Indonesia DTA – Credit method'],
            ['KR', 'TH', 'credit',      'South Korea-Thailand DTA – Credit method'],
            ['KR', 'PH', 'credit',      'South Korea-Philippines DTA – Credit method'],
            ['KR', 'VN', 'credit',      'South Korea-Vietnam DTA – Credit method'],
            ['KR', 'NZ', 'credit',      'South Korea-New Zealand DTA – Credit method'],
            ['KR', 'ZA', 'credit',      'South Korea-South Africa DTA – Credit method'],
            ['KR', 'AE', 'exemption',   'South Korea-UAE DTA – Exemption method'],
            ['KR', 'SA', 'exemption',   'South Korea-Saudi Arabia DTA – Exemption method'],
            ['KR', 'IL', 'credit',      'South Korea-Israel DTA – Credit method'],
            ['KR', 'TR', 'credit',      'South Korea-Turkey DTA – Credit method'],
            ['KR', 'RU', 'credit',      'South Korea-Russia DTA – Credit method'],
            ['KR', 'MX', 'credit',      'South Korea-Mexico DTA – Credit method'],
            ['KR', 'CA', 'credit',      'South Korea-Canada DTA – Credit method'],
            ['KR', 'PL', 'credit',      'South Korea-Poland DTA – Credit method'],
            ['KR', 'CZ', 'credit',      'South Korea-Czech Republic DTA – Credit method'],
            ['KR', 'HU', 'credit',      'South Korea-Hungary DTA – Credit method'],
            ['KR', 'RO', 'credit',      'South Korea-Romania DTA – Credit method'],

            // ── India bilateral treaties ───────────────────────────────────────────
            ['IN', 'AU', 'credit',      'India-Australia DTA – Foreign tax credit method'],
            ['IN', 'CA', 'credit',      'India-Canada DTA – Foreign tax credit method'],
            ['IN', 'MY', 'credit',      'India-Malaysia DTA – Credit method'],
            ['IN', 'TH', 'credit',      'India-Thailand DTA – Credit method'],
            ['IN', 'ID', 'credit',      'India-Indonesia DTA – Credit method'],
            ['IN', 'VN', 'credit',      'India-Vietnam DTA – Credit method'],
            ['IN', 'HK', 'credit',      'India-Hong Kong DTA – Credit method'],
            ['IN', 'AE', 'exemption',   'India-UAE DTA – Exemption method'],
            ['IN', 'SA', 'credit',      'Saudi Arabia-India DTA – Credit method'],
            ['IN', 'QA', 'credit',      'India-Qatar DTA – Credit method'],
            ['IN', 'KW', 'credit',      'India-Kuwait DTA – Credit method'],
            ['IN', 'OM', 'credit',      'India-Oman DTA – Credit method'],
            ['IN', 'BH', 'credit',      'India-Bahrain DTA – Credit method'],
            ['IN', 'IL', 'credit',      'India-Israel DTA – Credit method'],
            ['IN', 'TR', 'credit',      'India-Turkey DTA – Credit method'],
            ['IN', 'ZA', 'credit',      'India-South Africa DTA – Credit method'],
            ['IN', 'KE', 'credit',      'India-Kenya DTA – Credit method'],
            ['IN', 'MX', 'credit',      'India-Mexico DTA – Credit method'],
            ['IN', 'RU', 'credit',      'India-Russia DTA – Credit method'],
            ['IN', 'PK', 'credit',      'India-Pakistan DTA – Credit method'],
            ['IN', 'LK', 'credit',      'India-Sri Lanka DTA – Credit method'],
            ['IN', 'BD', 'credit',      'India-Bangladesh DTA – Credit method'],
            ['IN', 'NP', 'credit',      'India-Nepal DTA – Credit method'],
            ['IN', 'PH', 'credit',      'India-Philippines DTA – Credit method'],
            ['IN', 'EG', 'credit',      'India-Egypt DTA – Credit method'],
            ['IN', 'MA', 'credit',      'India-Morocco DTA – Credit method'],
            ['IN', 'TZ', 'credit',      'India-Tanzania DTA – Credit method'],
            ['IN', 'UG', 'credit',      'India-Uganda DTA – Credit method'],

            // ── China bilateral treaties ───────────────────────────────────────────
            ['CN', 'AU', 'credit',      'China-Australia DTA – Foreign tax credit method'],
            ['CN', 'CA', 'credit',      'China-Canada DTA – Foreign tax credit method'],
            ['CN', 'NZ', 'credit',      'China-New Zealand DTA – Credit method'],
            ['CN', 'MY', 'credit',      'China-Malaysia DTA – Credit method'],
            ['CN', 'TH', 'credit',      'China-Thailand DTA – Credit method'],
            ['CN', 'ID', 'credit',      'China-Indonesia DTA – Credit method'],
            ['CN', 'PH', 'credit',      'China-Philippines DTA – Credit method'],
            ['CN', 'VN', 'credit',      'China-Vietnam DTA – Credit method'],
            ['CN', 'AE', 'exemption',   'China-UAE DTA – Exemption method'],
            ['CN', 'SA', 'credit',      'China-Saudi Arabia DTA – Credit method'],
            ['CN', 'IL', 'credit',      'China-Israel DTA – Credit method'],
            ['CN', 'TR', 'credit',      'China-Turkey DTA – Credit method'],
            ['CN', 'RU', 'credit',      'China-Russia DTA – Credit method'],
            ['CN', 'ZA', 'credit',      'China-South Africa DTA – Credit method'],
            ['CN', 'EG', 'credit',      'China-Egypt DTA – Credit method'],
            ['CN', 'NG', 'credit',      'China-Nigeria DTA – Credit method'],
            ['CN', 'KE', 'credit',      'China-Kenya DTA – Credit method'],
            ['CN', 'ET', 'credit',      'China-Ethiopia DTA – Credit method'],
            ['CN', 'PK', 'credit',      'China-Pakistan DTA – Credit method'],
            ['CN', 'LK', 'credit',      'China-Sri Lanka DTA – Credit method'],
            ['CN', 'BD', 'credit',      'China-Bangladesh DTA – Credit method'],
            ['CN', 'MX', 'credit',      'China-Mexico DTA – Credit method'],
            ['CN', 'BR', 'credit',      'China-Brazil DTA – Credit method'],

            // ── Hong Kong bilateral treaties ───────────────────────────────────────
            ['HK', 'AU', 'exemption',   'Hong Kong-Australia DTA – Exemption method'],
            ['HK', 'CA', 'credit',      'Hong Kong-Canada DTA – Foreign tax credit method'],
            ['HK', 'JP', 'credit',      'Hong Kong-Japan DTA – Credit method'],
            ['HK', 'KR', 'credit',      'South Korea-Hong Kong DTA – Credit method'],
            ['HK', 'NZ', 'exemption',   'Hong Kong-New Zealand DTA – Exemption method'],
            ['HK', 'IN', 'credit',      'India-Hong Kong DTA – Credit method'],
            ['HK', 'AE', 'exemption',   'Hong Kong-UAE DTA – Exemption method'],
            ['HK', 'IL', 'credit',      'Hong Kong-Israel DTA – Credit method'],
            ['HK', 'ZA', 'credit',      'Hong Kong-South Africa DTA – Credit method'],
            ['HK', 'IT', 'credit',      'Hong Kong-Italy DTA – Credit method'],
            ['HK', 'ES', 'credit',      'Hong Kong-Spain DTA – Credit method'],
            ['HK', 'NL', 'credit',      'Hong Kong-Netherlands DTA – Credit method'],
            ['HK', 'BE', 'credit',      'Hong Kong-Belgium DTA – Credit method'],
            ['HK', 'AT', 'credit',      'Hong Kong-Austria DTA – Credit method'],
            ['HK', 'CH', 'credit',      'Hong Kong-Switzerland DTA – Credit method'],
            ['HK', 'SE', 'credit',      'Hong Kong-Sweden DTA – Credit method'],
            ['HK', 'IE', 'credit',      'Hong Kong-Ireland DTA – Credit method'],
            ['HK', 'LU', 'credit',      'Hong Kong-Luxembourg DTA – Credit method'],

            // ── Australia bilateral treaties ───────────────────────────────────────
            ['AU', 'NZ', 'credit',      'Australia-New Zealand DTA – Foreign tax credit method'],
            ['AU', 'MY', 'credit',      'Australia-Malaysia DTA – Credit method'],
            ['AU', 'TH', 'credit',      'Australia-Thailand DTA – Credit method'],
            ['AU', 'ID', 'credit',      'Australia-Indonesia DTA – Credit method'],
            ['AU', 'PH', 'credit',      'Australia-Philippines DTA – Credit method'],
            ['AU', 'VN', 'credit',      'Australia-Vietnam DTA – Credit method'],
            ['AU', 'ZA', 'credit',      'South Africa-Australia DTA – Credit method'],
            ['AU', 'AE', 'exemption',   'Australia-UAE DTA – Exemption method'],
            ['AU', 'IL', 'credit',      'Australia-Israel DTA – Credit method'],
            ['AU', 'TR', 'credit',      'Australia-Turkey DTA – Credit method'],
            ['AU', 'RU', 'credit',      'Australia-Russia DTA – Credit method'],
            ['AU', 'IN', 'credit',      'India-Australia DTA – Credit method'],
            ['AU', 'MX', 'credit',      'Australia-Mexico DTA – Credit method'],

            // ── Middle East treaties ───────────────────────────────────────────────
            ['AE', 'IN', 'exemption',   'India-UAE DTA – Exemption method'],
            ['AE', 'SA', 'exemption',   'UAE-Saudi Arabia DTA – GCC Exemption framework'],
            ['AE', 'QA', 'exemption',   'UAE-Qatar DTA – GCC Exemption framework'],
            ['AE', 'KW', 'exemption',   'UAE-Kuwait DTA – GCC Exemption framework'],
            ['AE', 'OM', 'exemption',   'UAE-Oman DTA – GCC Exemption framework'],
            ['AE', 'BH', 'exemption',   'UAE-Bahrain DTA – GCC Exemption framework'],
            ['AE', 'EG', 'credit',      'UAE-Egypt DTA – Credit method'],
            ['AE', 'MA', 'credit',      'UAE-Morocco DTA – Credit method'],
            ['AE', 'TR', 'credit',      'UAE-Turkey DTA – Credit method'],
            ['AE', 'ZA', 'credit',      'UAE-South Africa DTA – Credit method'],
            ['AE', 'KR', 'exemption',   'South Korea-UAE DTA – Exemption method'],
            ['AE', 'NL', 'exemption',   'Netherlands-UAE DTA – Exemption method'],
            ['AE', 'CH', 'exemption',   'Switzerland-UAE DTA – Exemption method'],
            ['AE', 'AT', 'exemption',   'Austria-UAE DTA – Exemption method'],
            ['AE', 'BE', 'credit',      'Belgium-UAE DTA – Credit method'],
            ['AE', 'MX', 'credit',      'UAE-Mexico DTA – Credit method'],
            ['AE', 'PK', 'exemption',   'UAE-Pakistan DTA – Exemption method'],
            ['SA', 'AE', 'exemption',   'Saudi Arabia-UAE DTA – GCC Exemption framework'],
            ['SA', 'QA', 'exemption',   'Saudi Arabia-Qatar DTA – GCC Exemption framework'],
            ['SA', 'KW', 'exemption',   'Saudi Arabia-Kuwait DTA – GCC Exemption framework'],
            ['SA', 'OM', 'exemption',   'Saudi Arabia-Oman DTA – GCC Exemption framework'],
            ['SA', 'BH', 'exemption',   'Saudi Arabia-Bahrain DTA – GCC Exemption framework'],
            ['SA', 'EG', 'credit',      'Saudi Arabia-Egypt DTA – Credit method'],
            ['SA', 'MA', 'credit',      'Saudi Arabia-Morocco DTA – Credit method'],
            ['SA', 'PK', 'credit',      'Saudi Arabia-Pakistan DTA – Credit method'],
            ['SA', 'TR', 'credit',      'Saudi Arabia-Turkey DTA – Credit method'],
            ['SA', 'ZA', 'credit',      'Saudi Arabia-South Africa DTA – Credit method'],
            ['QA', 'IN', 'credit',      'India-Qatar DTA – Credit method'],
            ['QA', 'GB', 'exemption',   'Qatar-UK DTA – Exemption method'],
            ['QA', 'FR', 'credit',      'Qatar-France DTA – Credit method'],
            ['QA', 'DE', 'credit',      'Qatar-Germany DTA – Credit method'],
            ['QA', 'JP', 'credit',      'Qatar-Japan DTA – Credit method'],
            ['KW', 'IN', 'credit',      'India-Kuwait DTA – Credit method'],
            ['KW', 'GB', 'exemption',   'Kuwait-UK DTA – Exemption method'],
            ['KW', 'FR', 'credit',      'Kuwait-France DTA – Credit method'],
            ['OM', 'IN', 'credit',      'India-Oman DTA – Credit method'],
            ['OM', 'GB', 'exemption',   'Oman-UK DTA – Exemption method'],
            ['BH', 'IN', 'credit',      'India-Bahrain DTA – Credit method'],
            ['BH', 'GB', 'exemption',   'Bahrain-UK DTA – Exemption method'],

            // ── Africa bilateral treaties ──────────────────────────────────────────
            ['ZA', 'IN', 'credit',      'India-South Africa DTA – Credit method'],
            ['ZA', 'CN', 'credit',      'China-South Africa DTA – Credit method'],
            ['ZA', 'IL', 'credit',      'Israel-South Africa DTA – Credit method'],
            ['ZA', 'TR', 'credit',      'Turkey-South Africa DTA – Credit method'],
            ['ZA', 'RU', 'credit',      'Russia-South Africa DTA – Credit method'],
            ['ZA', 'IT', 'credit',      'Italy-South Africa DTA – Credit method'],
            ['ZA', 'FR', 'credit',      'France-South Africa DTA – Credit method'],
            ['ZA', 'BE', 'credit',      'Belgium-South Africa DTA – Credit method'],
            ['ZA', 'SE', 'credit',      'Sweden-South Africa DTA – Credit method'],
            ['ZA', 'NO', 'credit',      'Norway-South Africa DTA – Credit method'],
            ['ZA', 'NG', 'credit',      'South Africa-Nigeria DTA – Credit method'],
            ['ZA', 'KE', 'credit',      'South Africa-Kenya DTA – Credit method'],
            ['ZA', 'MU', 'credit',      'South Africa-Mauritius DTA – Credit method'],
            ['ZA', 'ZM', 'credit',      'South Africa-Zambia DTA – Credit method'],
            ['ZA', 'ZW', 'credit',      'South Africa-Zimbabwe DTA – Credit method'],
            ['ZA', 'BW', 'credit',      'South Africa-Botswana DTA – Credit method'],
            ['ZA', 'NA', 'credit',      'South Africa-Namibia DTA – Credit method'],
            ['ZA', 'MZ', 'credit',      'South Africa-Mozambique DTA – Credit method'],
            ['ZA', 'LS', 'credit',      'South Africa-Lesotho DTA – Credit method'],
            ['ZA', 'SZ', 'credit',      'South Africa-Eswatini DTA – Credit method'],
            ['EG', 'DE', 'credit',      'Germany-Egypt DTA – Credit method'],
            ['EG', 'FR', 'credit',      'France-Egypt DTA – Credit method'],
            ['EG', 'IT', 'credit',      'Italy-Egypt DTA – Credit method'],
            ['EG', 'JP', 'credit',      'Japan-Egypt DTA – Credit method'],
            ['EG', 'CN', 'credit',      'China-Egypt DTA – Credit method'],
            ['EG', 'TR', 'credit',      'Turkey-Egypt DTA – Credit method'],
            ['EG', 'RU', 'credit',      'Russia-Egypt DTA – Credit method'],
            ['EG', 'IN', 'credit',      'India-Egypt DTA – Credit method'],
            ['MA', 'FR', 'credit',      'France-Morocco DTA – Credit method'],
            ['MA', 'ES', 'credit',      'Spain-Morocco DTA – Credit method'],
            ['MA', 'DE', 'credit',      'Germany-Morocco DTA – Credit method'],
            ['MA', 'AE', 'credit',      'UAE-Morocco DTA – Credit method'],
            ['MA', 'SA', 'credit',      'Saudi Arabia-Morocco DTA – Credit method'],
            ['NG', 'GB', 'credit',      'UK-Nigeria DTA – Credit method'],
            ['NG', 'CN', 'credit',      'China-Nigeria DTA – Credit method'],
            ['KE', 'GB', 'credit',      'UK-Kenya DTA – Credit method'],
            ['KE', 'CN', 'credit',      'China-Kenya DTA – Credit method'],
            ['KE', 'IN', 'credit',      'India-Kenya DTA – Credit method'],
            ['MU', 'IN', 'credit',      'India-Mauritius DTA – Credit method'],
            ['MU', 'CN', 'credit',      'China-Mauritius DTA – Credit method'],
            ['MU', 'FR', 'credit',      'France-Mauritius DTA – Credit method'],
            ['MU', 'SA', 'credit',      'Saudi Arabia-Mauritius DTA – Credit method'],
              // ── Canada bilateral treaties ──────────────────────────────────────────
            ['CA', 'AU', 'credit',      'Canada-Australia DTA – Foreign tax credit method'],
            ['CA', 'BR', 'credit',      'Canada-Brazil DTA – Foreign tax credit method'],
            ['CA', 'MX', 'credit',      'Canada-Mexico DTA – Foreign tax credit method'],
            ['CA', 'FR', 'credit',      'Canada-France DTA – Foreign tax credit method'],
            ['CA', 'IN', 'credit',      'India-Canada DTA – Foreign tax credit method'],
            ['CA', 'CN', 'credit',      'China-Canada DTA – Foreign tax credit method'],
            ['CA', 'JP', 'credit',      'Japan-Canada DTA – Credit method'],
            ['CA', 'KR', 'credit',      'South Korea-Canada DTA – Credit method'],
            ['CA', 'NZ', 'credit',      'New Zealand-Canada DTA – Credit method'],
            ['CA', 'ZA', 'credit',      'South Africa-Canada DTA – Credit method'],
            ['CA', 'IL', 'credit',      'Israel-Canada DTA – Credit method'],
            ['CA', 'TR', 'credit',      'Turkey-Canada DTA – Credit method'],
            ['CA', 'RU', 'credit',      'Russia-Canada DTA – Credit method'],
            ['CA', 'PL', 'credit',      'Poland-Canada DTA – Credit method'],
            ['CA', 'CZ', 'credit',      'Czech Republic-Canada DTA – Credit method'],
            ['CA', 'HU', 'credit',      'Hungary-Canada DTA – Credit method'],
            ['CA', 'RO', 'credit',      'Romania-Canada DTA – Credit method'],
            ['CA', 'SK', 'credit',      'Slovakia-Canada DTA – Credit method'],
            ['CA', 'SE', 'credit',      'Sweden-Canada DTA – Credit method'],
            ['CA', 'DK', 'credit',      'Denmark-Canada DTA – Credit method'],
            ['CA', 'NO', 'credit',      'Norway-Canada DTA – Credit method'],
            ['CA', 'FI', 'credit',      'Finland-Canada DTA – Credit method'],
            ['CA', 'BE', 'credit',      'Belgium-Canada DTA – Credit method'],
            ['CA', 'CH', 'credit',      'Switzerland-Canada DTA – Credit method'],
            ['CA', 'AT', 'credit',      'Austria-Canada DTA – Credit method'],
            ['CA', 'IE', 'credit',      'Ireland-Canada DTA – Credit method'],
            ['CA', 'SG', 'credit',      'Singapore-Canada DTA – Credit method'],
            ['CA', 'MY', 'credit',      'Malaysia-Canada DTA – Credit method'],
            ['CA', 'HK', 'credit',      'Hong Kong-Canada DTA – Credit method'],
            ['CA', 'BB', 'credit',      'Barbados-Canada DTA – Credit method'],
            ['CA', 'EG', 'credit',      'Egypt-Canada DTA – Credit method'],
            ['CA', 'PE', 'credit',      'Peru-Canada DTA – Credit method'],
            ['CA', 'CO', 'credit',      'Colombia-Canada DTA – Credit method'],
 
            // ── Latin America bilateral treaties ───────────────────────────────────
            ['MX', 'ES', 'credit',      'Mexico-Spain DTA – Foreign tax credit method'],
            ['MX', 'BR', 'credit',      'Mexico-Brazil DTA – Credit method'],
            ['MX', 'AR', 'credit',      'Mexico-Argentina DTA – Credit method'],
            ['MX', 'CL', 'credit',      'Chile-Mexico DTA – Credit method'],
            ['MX', 'CO', 'credit',      'Mexico-Colombia DTA – Credit method'],
            ['MX', 'PE', 'credit',      'Mexico-Peru DTA – Credit method'],
            ['MX', 'JP', 'credit',      'Japan-Mexico DTA – Credit method'],
            ['MX', 'KR', 'credit',      'South Korea-Mexico DTA – Credit method'],
            ['MX', 'SG', 'credit',      'Singapore-Mexico DTA – Credit method'],
            ['MX', 'AU', 'credit',      'Australia-Mexico DTA – Credit method'],
            ['MX', 'NZ', 'credit',      'New Zealand-Mexico DTA – Credit method'],
            ['MX', 'AE', 'credit',      'UAE-Mexico DTA – Credit method'],
            ['MX', 'IL', 'credit',      'Israel-Mexico DTA – Credit method'],
            ['MX', 'TR', 'credit',      'Turkey-Mexico DTA – Credit method'],
            ['MX', 'RU', 'credit',      'Russia-Mexico DTA – Credit method'],
            ['MX', 'PL', 'credit',      'Poland-Mexico DTA – Credit method'],
            ['MX', 'CZ', 'credit',      'Czech Republic-Mexico DTA – Credit method'],
            ['MX', 'HU', 'credit',      'Hungary-Mexico DTA – Credit method'],
            ['MX', 'RO', 'credit',      'Romania-Mexico DTA – Credit method'],
            ['MX', 'SK', 'credit',      'Slovakia-Mexico DTA – Credit method'],
            ['MX', 'SE', 'credit',      'Sweden-Mexico DTA – Credit method'],
            ['MX', 'DK', 'credit',      'Denmark-Mexico DTA – Credit method'],
            ['MX', 'NO', 'credit',      'Norway-Mexico DTA – Credit method'],
            ['MX', 'FI', 'credit',      'Finland-Mexico DTA – Credit method'],
            ['MX', 'BE', 'credit',      'Belgium-Mexico DTA – Credit method'],
            ['MX', 'CH', 'credit',      'Switzerland-Mexico DTA – Credit method'],
            ['MX', 'AT', 'credit',      'Austria-Mexico DTA – Credit method'],
            ['MX', 'IE', 'credit',      'Ireland-Mexico DTA – Credit method'],
            ['MX', 'NL', 'credit',      'Netherlands-Mexico DTA – Credit method'],
            ['MX', 'PA', 'credit',      'Panama-Mexico DTA – Credit method'],
            ['BR', 'PT', 'credit',      'Brazil-Portugal DTA – Historical ties, credit method'],
            ['BR', 'AR', 'credit',      'Argentina-Brazil DTA – Credit method'],
            ['BR', 'CL', 'credit',      'Chile-Brazil DTA – Credit method'],
            ['BR', 'CO', 'credit',      'Brazil-Colombia DTA – Credit method'],
            ['BR', 'PE', 'credit',      'Brazil-Peru DTA – Credit method'],
            ['BR', 'ES', 'credit',      'Spain-Brazil DTA – Credit method'],
            ['BR', 'IT', 'credit',      'Italy-Brazil DTA – Credit method'],
            ['BR', 'JP', 'credit',      'Japan-Brazil DTA – Credit method'],
            ['BR', 'KR', 'credit',      'South Korea-Brazil DTA – Credit method'],
            ['BR', 'SG', 'credit',      'Singapore-Brazil DTA – Credit method'],
            ['BR', 'AU', 'credit',      'Australia-Brazil DTA – Credit method'],
            ['BR', 'AE', 'credit',      'UAE-Brazil DTA – Credit method'],
            ['BR', 'IL', 'credit',      'Israel-Brazil DTA – Credit method'],
            ['BR', 'TR', 'credit',      'Turkey-Brazil DTA – Credit method'],
            ['AR', 'CL', 'credit',      'Argentina-Chile DTA – Credit method'],
            ['AR', 'CO', 'credit',      'Argentina-Colombia DTA – Credit method'],
            ['CL', 'CO', 'credit',      'Chile-Colombia DTA – Credit method'],
            ['CL', 'PE', 'credit',      'Chile-Peru DTA – Credit method'],
            ['CO', 'PE', 'credit',      'Colombia-Peru DTA – Credit method'],
            ['CO', 'ES', 'credit',      'Spain-Colombia DTA – Credit method'],
            ['CO', 'PT', 'credit',      'Portugal-Colombia DTA – Credit method'],
            ['PE', 'ES', 'credit',      'Spain-Peru DTA – Credit method'],
            ['PE', 'PT', 'credit',      'Portugal-Peru DTA – Credit method'],
 
            // ── Eastern Europe & CIS bilateral treaties ────────────────────────────
            ['RU', 'CN', 'credit',      'Russia-China DTA – Credit method'],
            ['RU', 'IN', 'credit',      'Russia-India DTA – Credit method'],
            ['RU', 'JP', 'credit',      'Russia-Japan DTA – Credit method'],
            ['RU', 'KR', 'credit',      'Russia-South Korea DTA – Credit method'],
            ['RU', 'SG', 'credit',      'Singapore-Russia DTA – Credit method'],
            ['RU', 'AE', 'credit',      'UAE-Russia DTA – Credit method'],
            ['RU', 'TR', 'credit',      'Turkey-Russia DTA – Credit method'],
            ['RU', 'IL', 'credit',      'Israel-Russia DTA – Credit method'],
            ['RU', 'ZA', 'credit',      'South Africa-Russia DTA – Credit method'],
            ['RU', 'EG', 'credit',      'Egypt-Russia DTA – Credit method'],
            ['RU', 'PL', 'credit',      'Poland-Russia DTA – Credit method'],
            ['RU', 'CZ', 'credit',      'Czech Republic-Russia DTA – Credit method'],
            ['RU', 'HU', 'credit',      'Hungary-Russia DTA – Credit method'],
            ['RU', 'RO', 'credit',      'Romania-Russia DTA – Credit method'],
            ['RU', 'BG', 'credit',      'Bulgaria-Russia DTA – Credit method'],
            ['RU', 'SK', 'credit',      'Slovakia-Russia DTA – Credit method'],
            ['RU', 'UA', 'credit',      'Russia-Ukraine DTA – Credit method'],
            ['RU', 'KZ', 'credit',      'Russia-Kazakhstan DTA – Credit method'],
            ['RU', 'BY', 'credit',      'Russia-Belarus DTA – Credit method'],
            ['RU', 'AM', 'credit',      'Russia-Armenia DTA – Credit method'],
            ['RU', 'GE', 'credit',      'Georgia-Russia DTA – Credit method'],
            ['RU', 'AZ', 'credit',      'Russia-Azerbaijan DTA – Credit method'],
            ['RU', 'UZ', 'credit',      'Russia-Uzbekistan DTA – Credit method'],
            ['RU', 'KG', 'credit',      'Russia-Kyrgyzstan DTA – Credit method'],
            ['RU', 'TJ', 'credit',      'Russia-Tajikistan DTA – Credit method'],
            ['RU', 'TM', 'credit',      'Russia-Turkmenistan DTA – Credit method'],
            ['RU', 'MD', 'credit',      'Russia-Moldova DTA – Credit method'],
            ['PL', 'CZ', 'credit',      'Poland-Czech Republic DTA – Credit method'],
            ['PL', 'SK', 'credit',      'Poland-Slovakia DTA – Credit method'],
            ['PL', 'HU', 'credit',      'Poland-Hungary DTA – Credit method'],
            ['PL', 'RO', 'credit',      'Poland-Romania DTA – Credit method'],
            ['PL', 'BG', 'credit',      'Poland-Bulgaria DTA – Credit method'],
            ['PL', 'UA', 'credit',      'Poland-Ukraine DTA – Credit method'],
            ['PL', 'BY', 'credit',      'Poland-Belarus DTA – Credit method'],
            ['PL', 'EE', 'credit',      'Poland-Estonia DTA – Credit method'],
            ['PL', 'LV', 'credit',      'Poland-Latvia DTA – Credit method'],
            ['PL', 'LT', 'credit',      'Poland-Lithuania DTA – Credit method'],
            ['CZ', 'SK', 'credit',      'Czech Republic-Slovakia DTA – Credit method'],
            ['CZ', 'HU', 'credit',      'Czech Republic-Hungary DTA – Credit method'],
            ['CZ', 'RO', 'credit',      'Czech Republic-Romania DTA – Credit method'],
            ['CZ', 'UA', 'credit',      'Czech Republic-Ukraine DTA – Credit method'],
            ['HU', 'RO', 'credit',      'Hungary-Romania DTA – Credit method'],
            ['HU', 'UA', 'credit',      'Hungary-Ukraine DTA – Credit method'],
            ['RO', 'BG', 'credit',      'Romania-Bulgaria DTA – Credit method'],
            ['RO', 'UA', 'credit',      'Romania-Ukraine DTA – Credit method'],
            ['UA', 'BY', 'credit',      'Ukraine-Belarus DTA – Credit method'],
            ['UA', 'KZ', 'credit',      'Ukraine-Kazakhstan DTA – Credit method'],
            ['UA', 'AZ', 'credit',      'Ukraine-Azerbaijan DTA – Credit method'],
            ['UA', 'AM', 'credit',      'Ukraine-Armenia DTA – Credit method'],
            ['UA', 'GE', 'credit',      'Ukraine-Georgia DTA – Credit method'],
            ['KZ', 'CN', 'credit',      'China-Kazakhstan DTA – Credit method'],
            ['KZ', 'AE', 'credit',      'UAE-Kazakhstan DTA – Credit method'],
            ['KZ', 'TR', 'credit',      'Turkey-Kazakhstan DTA – Credit method'],
            ['GE', 'AE', 'exemption',   'Georgia-UAE DTA – Exemption method'],
            ['GE', 'TR', 'credit',      'Georgia-Turkey DTA – Credit method'],
 
            // ── ASEAN intra-regional treaties ─────────────────────────────────────
            ['TH', 'MY', 'credit',      'Thailand-Malaysia DTA – Credit method'],
            ['TH', 'ID', 'credit',      'Thailand-Indonesia DTA – Credit method'],
            ['TH', 'PH', 'credit',      'Thailand-Philippines DTA – Credit method'],
            ['TH', 'VN', 'credit',      'Thailand-Vietnam DTA – Credit method'],
            ['MY', 'ID', 'credit',      'Malaysia-Indonesia DTA – Credit method'],
            ['MY', 'PH', 'credit',      'Malaysia-Philippines DTA – Credit method'],
            ['MY', 'VN', 'credit',      'Malaysia-Vietnam DTA – Credit method'],
            ['MY', 'IN', 'credit',      'India-Malaysia DTA – Credit method'],
            ['MY', 'CN', 'credit',      'China-Malaysia DTA – Credit method'],
            ['MY', 'JP', 'credit',      'Japan-Malaysia DTA – Credit method'],
            ['MY', 'KR', 'credit',      'South Korea-Malaysia DTA – Credit method'],
            ['MY', 'AU', 'credit',      'Australia-Malaysia DTA – Credit method'],
            ['MY', 'NZ', 'credit',      'New Zealand-Malaysia DTA – Credit method'],
            ['MY', 'AE', 'exemption',   'UAE-Malaysia DTA – Exemption method'],
            ['ID', 'PH', 'credit',      'Indonesia-Philippines DTA – Credit method'],
            ['ID', 'VN', 'credit',      'Indonesia-Vietnam DTA – Credit method'],
            ['ID', 'AU', 'credit',      'Australia-Indonesia DTA – Credit method'],
            ['ID', 'CN', 'credit',      'China-Indonesia DTA – Credit method'],
            ['ID', 'JP', 'credit',      'Japan-Indonesia DTA – Credit method'],
            ['ID', 'KR', 'credit',      'South Korea-Indonesia DTA – Credit method'],
            ['ID', 'AE', 'credit',      'UAE-Indonesia DTA – Credit method'],
            ['PH', 'VN', 'credit',      'Philippines-Vietnam DTA – Credit method'],
            ['PH', 'CN', 'credit',      'China-Philippines DTA – Credit method'],
            ['PH', 'KR', 'credit',      'South Korea-Philippines DTA – Credit method'],
            ['VN', 'CN', 'credit',      'China-Vietnam DTA – Credit method'],
            ['VN', 'KR', 'credit',      'South Korea-Vietnam DTA – Credit method'],
            ['VN', 'JP', 'credit',      'Japan-Vietnam DTA – Credit method'],
            ['VN', 'AU', 'credit',      'Australia-Vietnam DTA – Credit method'],
            ['VN', 'AE', 'credit',      'UAE-Vietnam DTA – Credit method'],
 
            // ── South Asia bilateral treaties ──────────────────────────────────────
            ['PK', 'CN', 'credit',      'China-Pakistan DTA – Credit method'],
            ['PK', 'AE', 'exemption',   'UAE-Pakistan DTA – Exemption method'],
            ['PK', 'SA', 'credit',      'Saudi Arabia-Pakistan DTA – Credit method'],
            ['PK', 'TR', 'credit',      'Turkey-Pakistan DTA – Credit method'],
            ['PK', 'KW', 'credit',      'Kuwait-Pakistan DTA – Credit method'],
            ['PK', 'OM', 'credit',      'Oman-Pakistan DTA – Credit method'],
            ['PK', 'QA', 'credit',      'Qatar-Pakistan DTA – Credit method'],
            ['LK', 'IN', 'credit',      'India-Sri Lanka DTA – Credit method'],
            ['LK', 'CN', 'credit',      'China-Sri Lanka DTA – Credit method'],
            ['BD', 'IN', 'credit',      'India-Bangladesh DTA – Credit method'],
            ['BD', 'CN', 'credit',      'China-Bangladesh DTA – Credit method'],
            ['BD', 'JP', 'credit',      'Japan-Bangladesh DTA – Credit method'],
            ['NP', 'IN', 'credit',      'India-Nepal DTA – Credit method'],
            ['NP', 'CN', 'credit',      'China-Nepal DTA – Credit method'],
 
            // ── Totalization Agreements (Social Security Treaties) ─────────────────
            ['US', 'GB', 'totalization', 'US-UK Totalization Agreement – Social Security'],
            ['US', 'CA', 'totalization', 'US-Canada Totalization Agreement – Social Security'],
            ['US', 'AU', 'totalization', 'US-Australia Totalization Agreement – Social Security'],
            ['US', 'DE', 'totalization', 'US-Germany Totalization Agreement – Social Security'],
            ['US', 'FR', 'totalization', 'US-France Totalization Agreement – Social Security'],
            ['US', 'IT', 'totalization', 'US-Italy Totalization Agreement – Social Security'],
            ['US', 'ES', 'totalization', 'US-Spain Totalization Agreement – Social Security'],
            ['US', 'JP', 'totalization', 'US-Japan Totalization Agreement – Social Security'],
            ['US', 'KR', 'totalization', 'US-South Korea Totalization Agreement – Social Security'],
            ['US', 'NL', 'totalization', 'US-Netherlands Totalization Agreement – Social Security'],
            ['US', 'BE', 'totalization', 'US-Belgium Totalization Agreement – Social Security'],
            ['US', 'CH', 'totalization', 'US-Switzerland Totalization Agreement – Social Security'],
            ['US', 'AT', 'totalization', 'US-Austria Totalization Agreement – Social Security'],
            ['US', 'SE', 'totalization', 'US-Sweden Totalization Agreement – Social Security'],
            ['US', 'DK', 'totalization', 'US-Denmark Totalization Agreement – Social Security'],
            ['US', 'NO', 'totalization', 'US-Norway Totalization Agreement – Social Security'],
            ['US', 'FI', 'totalization', 'US-Finland Totalization Agreement – Social Security'],
            ['US', 'IE', 'totalization', 'US-Ireland Totalization Agreement – Social Security'],
            ['US', 'PT', 'totalization', 'US-Portugal Totalization Agreement – Social Security'],
            ['US', 'PL', 'totalization', 'US-Poland Totalization Agreement – Social Security'],
            ['US', 'CZ', 'totalization', 'US-Czech Republic Totalization Agreement – Social Security'],
            ['US', 'HU', 'totalization', 'US-Hungary Totalization Agreement – Social Security'],
            ['US', 'SK', 'totalization', 'US-Slovakia Totalization Agreement – Social Security'],
            ['US', 'MX', 'totalization', 'US-Mexico Totalization Agreement – Social Security (pending)'],
            ['US', 'CL', 'totalization', 'US-Chile Totalization Agreement – Social Security'],
            ['US', 'GR', 'totalization', 'US-Greece Totalization Agreement – Social Security'],
            ['US', 'IL', 'totalization', 'US-Israel Totalization Agreement – Social Security'],
 
            // ── Ireland & Luxembourg (Special treaty hubs) ────────────────────────
            ['IE', 'DE', 'credit',      'Ireland-Germany DTA – Credit method'],
            ['IE', 'FR', 'credit',      'Ireland-France DTA – Credit method'],
            ['IE', 'ES', 'credit',      'Ireland-Spain DTA – Credit method'],
            ['IE', 'IT', 'credit',      'Ireland-Italy DTA – Credit method'],
            ['IE', 'NL', 'credit',      'Ireland-Netherlands DTA – Credit method'],
            ['IE', 'BE', 'credit',      'Ireland-Belgium DTA – Credit method'],
            ['IE', 'LU', 'credit',      'Ireland-Luxembourg DTA – Credit method'],
            ['IE', 'CH', 'credit',      'Ireland-Switzerland DTA – Credit method'],
            ['IE', 'AT', 'credit',      'Ireland-Austria DTA – Credit method'],
            ['IE', 'JP', 'credit',      'Ireland-Japan DTA – Credit method'],
            ['IE', 'CN', 'credit',      'Ireland-China DTA – Credit method'],
            ['IE', 'IN', 'credit',      'Ireland-India DTA – Credit method'],
            ['IE', 'SG', 'credit',      'Ireland-Singapore DTA – Credit method'],
            ['IE', 'AU', 'credit',      'Ireland-Australia DTA – Credit method'],
            ['IE', 'ZA', 'credit',      'Ireland-South Africa DTA – Credit method'],
            ['IE', 'AE', 'exemption',   'Ireland-UAE DTA – Exemption method'],
            ['LU', 'FR', 'credit',      'Luxembourg-France DTA – Credit method'],
            ['LU', 'DE', 'credit',      'Luxembourg-Germany DTA – Credit method'],
            ['LU', 'BE', 'credit',      'Luxembourg-Belgium DTA – Credit method'],
            ['LU', 'CH', 'credit',      'Luxembourg-Switzerland DTA – Credit method'],
            ['LU', 'AT', 'credit',      'Luxembourg-Austria DTA – Credit method'],
            ['LU', 'JP', 'credit',      'Luxembourg-Japan DTA – Credit method'],
            ['LU', 'CN', 'credit',      'Luxembourg-China DTA – Credit method'],
            ['LU', 'SG', 'credit',      'Luxembourg-Singapore DTA – Credit method'],
            ['LU', 'AU', 'credit',      'Luxembourg-Australia DTA – Credit method'],
            ['LU', 'AE', 'exemption',   'Luxembourg-UAE DTA – Exemption method'],
 
            // ── Israel, Turkey cross-treaties ─────────────────────────────────────
            ['IL', 'TR', 'credit',      'Israel-Turkey DTA – Credit method'],
            ['IL', 'IN', 'credit',      'India-Israel DTA – Credit method'],
            ['IL', 'CN', 'credit',      'China-Israel DTA – Credit method'],
            ['IL', 'JP', 'credit',      'Japan-Israel DTA – Credit method'],
            ['IL', 'KR', 'credit',      'South Korea-Israel DTA – Credit method'],
            ['IL', 'SG', 'credit',      'Singapore-Israel DTA – Credit method'],
            ['IL', 'AU', 'credit',      'Australia-Israel DTA – Credit method'],
            ['IL', 'ZA', 'credit',      'South Africa-Israel DTA – Credit method'],
            ['IL', 'MX', 'credit',      'Israel-Mexico DTA – Credit method'],
            ['IL', 'BR', 'credit',      'Israel-Brazil DTA – Credit method'],
            ['TR', 'AE', 'credit',      'UAE-Turkey DTA – Credit method'],
            ['TR', 'SA', 'credit',      'Saudi Arabia-Turkey DTA – Credit method'],
            ['TR', 'QA', 'credit',      'Qatar-Turkey DTA – Credit method'],
            ['TR', 'IL', 'credit',      'Israel-Turkey DTA – Credit method'],
            ['TR', 'ZA', 'credit',      'South Africa-Turkey DTA – Credit method'],
            ['TR', 'EG', 'credit',      'Turkey-Egypt DTA – Credit method'],
            ['TR', 'MA', 'credit',      'Turkey-Morocco DTA – Credit method'],
            ['TR', 'PK', 'credit',      'Turkey-Pakistan DTA – Credit method'],
            ['TR', 'KZ', 'credit',      'Turkey-Kazakhstan DTA – Credit method'],
            ['TR', 'AZ', 'credit',      'Turkey-Azerbaijan DTA – Credit method'],
            ['TR', 'GE', 'credit',      'Georgia-Turkey DTA – Credit method'],
            ['TR', 'SG', 'credit',      'Singapore-Turkey DTA – Credit method'],
            ['TR', 'IN', 'credit',      'India-Turkey DTA – Credit method'],
            ['TR', 'CN', 'credit',      'China-Turkey DTA – Credit method'],
            ['TR', 'JP', 'credit',      'Japan-Turkey DTA – Credit method'],
            ['TR', 'KR', 'credit',      'South Korea-Turkey DTA – Credit method'],
            ['TR', 'AU', 'credit',      'Australia-Turkey DTA – Credit method'],
            ['TR', 'BR', 'credit',      'Turkey-Brazil DTA – Credit method'],
            ['TR', 'MX', 'credit',      'Turkey-Mexico DTA – Credit method'],
 
            // ── New Zealand cross-treaties ─────────────────────────────────────────
            ['NZ', 'AU', 'credit',      'New Zealand-Australia DTA – Credit method'],
            ['NZ', 'SG', 'credit',      'New Zealand-Singapore DTA – Credit method'],
            ['NZ', 'JP', 'credit',      'New Zealand-Japan DTA – Credit method'],
            ['NZ', 'CN', 'credit',      'New Zealand-China DTA – Credit method'],
            ['NZ', 'KR', 'credit',      'New Zealand-South Korea DTA – Credit method'],
            ['NZ', 'IN', 'credit',      'New Zealand-India DTA – Credit method'],
            ['NZ', 'MY', 'credit',      'New Zealand-Malaysia DTA – Credit method'],
            ['NZ', 'HK', 'exemption',   'Hong Kong-New Zealand DTA – Exemption method'],
            ['NZ', 'AE', 'exemption',   'UAE-New Zealand DTA – Exemption method'],
            ['NZ', 'ZA', 'credit',      'South Africa-New Zealand DTA – Credit method'],
 
            // ── Portugal & Greece (digital nomad hubs) ────────────────────────────
            ['PT', 'BR', 'credit',      'Portugal-Brazil DTA – Historical ties, credit method'],
            ['PT', 'ES', 'credit',      'Portugal-Spain DTA – Iberian neighbors, credit method'],
            ['PT', 'CN', 'credit',      'Portugal-China DTA – Credit method'],
            ['PT', 'JP', 'credit',      'Portugal-Japan DTA – Credit method'],
            ['PT', 'AE', 'credit',      'Portugal-UAE DTA – Credit method'],
            ['PT', 'IN', 'credit',      'Portugal-India DTA – Credit method'],
            ['PT', 'ZA', 'credit',      'Portugal-South Africa DTA – Credit method'],
            ['PT', 'MZ', 'credit',      'Portugal-Mozambique DTA – Credit method'],
            ['PT', 'AO', 'credit',      'Portugal-Angola DTA – Credit method'],
            ['PT', 'CV', 'credit',      'Portugal-Cape Verde DTA – Credit method'],
            ['GR', 'CY', 'credit',      'Greece-Cyprus DTA – Credit method'],
            ['GR', 'AL', 'credit',      'Greece-Albania DTA – Credit method'],
            ['GR', 'IN', 'credit',      'Greece-India DTA – Credit method'],
            ['GR', 'CN', 'credit',      'Greece-China DTA – Credit method'],
            ['GR', 'AE', 'credit',      'Greece-UAE DTA – Credit method'],
            ['GR', 'SA', 'credit',      'Greece-Saudi Arabia DTA – Credit method'],
            ['CY', 'RU', 'credit',      'Cyprus-Russia DTA – Credit method'],
            ['CY', 'AE', 'exemption',   'Cyprus-UAE DTA – Exemption method'],
            ['CY', 'SA', 'credit',      'Cyprus-Saudi Arabia DTA – Credit method'],
            ['CY', 'IN', 'credit',      'Cyprus-India DTA – Credit method'],
            ['CY', 'CN', 'credit',      'Cyprus-China DTA – Credit method'],
            ['MT', 'IT', 'credit',      'Malta-Italy DTA – Credit method'],
            ['MT', 'AE', 'exemption',   'Malta-UAE DTA – Exemption method'],
            ['MT', 'SA', 'credit',      'Malta-Saudi Arabia DTA – Credit method'],
            ['MT', 'IN', 'credit',      'Malta-India DTA – Credit method'],
            ['MT', 'CN', 'credit',      'Malta-China DTA – Credit method'],
        ];

        $records = [];
        foreach ($treaties as [$a, $b, $type, $desc]) {
            $aId = $id($a);
            $bId = $id($b);
            if (!$aId || !$bId) continue;

            $records[] = [
                'country_a_id'        => $aId,
                'country_b_id'        => $bId,
                'treaty_type'         => $type,
                'applicable_tax_year' => 2026,
                'description'         => $desc,
                'is_active'           => true,
                'created_at'          => $now,
                'updated_at'          => $now,
            ];
        }

        foreach (array_chunk($records, 50) as $chunk) {
            DB::table('tax_treaties')->insertOrIgnore($chunk);
        }
    }
}
